import { layouts, coaxial } from './lib/layout';
import type { ParameterDefinition, Parameters, PartDefinition } from '../../core/types';
export const defaults: Parameters = {
  layout: 'quad-x',
  rearAngle: 35,
  coaxialGap: 35,
  armStyle: 'flat',
  wheelbase: 225,
  bodyLength: 100,
  bodyWidth: 42,
  plate: 2.5,
  gap: 27,
  armThickness: 5,
  armWidth: 14,
  armAngle: 45,
  tubeWall: 1,
  stackPitch: 30.5,
  motorPitch: 16,
  hole: 3.2,
  shaftClearance: 8,
  spacerDiameter: 5,
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'layout',
    label: 'Frame configuration',
    type: 'select',
    group: 'Configuration',
    options: layouts,
  },
  {
    key: 'armStyle',
    label: 'Arm construction',
    type: 'select',
    group: 'Construction',
    options: [
      { value: 'flat', label: 'Flat plate arms' },
      { value: 'tube', label: 'Round tube arms' },
    ],
  },
  {
    key: 'wheelbase',
    label: 'Motor circle diameter',
    type: 'number',
    group: 'Dimensions',
    min: 70,
    max: 1600,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'bodyLength',
    label: 'Centre plate length',
    type: 'number',
    group: 'Dimensions',
    min: 30,
    max: 400,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'bodyWidth',
    label: 'Centre plate width',
    type: 'number',
    group: 'Dimensions',
    min: 25,
    max: 400,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'plate',
    label: 'Top and bottom plate thickness',
    type: 'number',
    group: 'Construction',
    min: 1,
    max: 10,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'gap',
    label: 'Clear space between plates',
    type: 'number',
    group: 'Construction',
    min: 10,
    max: 100,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'armThickness',
    label: 'Flat arm thickness',
    type: 'number',
    group: 'Arms',
    min: 1,
    max: 15,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'armWidth',
    label: 'Arm width / tube outside diameter',
    type: 'number',
    group: 'Arms',
    min: 6,
    max: 50,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'armAngle',
    label: 'Front arm angle from nose',
    type: 'number',
    group: 'Arms',
    min: 25,
    max: 65,
    step: 0.1,
    unit: '\u00b0',
  },
  {
    key: 'rearAngle',
    label: 'Rear arm angle from tail',
    type: 'number',
    group: 'Arms',
    min: 25,
    max: 65,
    step: 0.1,
    unit: '°',
    visibleWhen: (p) => p.layout === 'quad-v',
  },
  {
    key: 'coaxialGap',
    label: 'Clear gap between motor plates',
    type: 'number',
    group: 'Mounting',
    min: 10,
    max: 150,
    step: 0.1,
    unit: 'mm',
    visibleWhen: coaxial,
  },
  {
    key: 'tubeWall',
    label: 'Tube wall thickness',
    type: 'number',
    group: 'Arms',
    min: 0.5,
    max: 5,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'stackPitch',
    label: 'Controller hole spacing',
    type: 'number',
    group: 'Mounting',
    min: 10,
    max: 100,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'motorPitch',
    label: 'Motor hole spacing',
    type: 'number',
    group: 'Mounting',
    min: 5,
    max: 40,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'hole',
    label: 'Mounting hole diameter',
    type: 'number',
    group: 'Mounting',
    min: 1.5,
    max: 8,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'shaftClearance',
    label: 'Motor shaft clearance',
    type: 'number',
    group: 'Mounting',
    min: 2,
    max: 20,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'spacerDiameter',
    label: 'Spacer diameter',
    type: 'number',
    group: 'Construction',
    min: 3,
    max: 15,
    step: 0.1,
    unit: 'mm',
  },
];
export const catalogSelection: NonNullable<PartDefinition['catalogSelection']> = [];

for (const field of parameters) {
  if (field.key === 'tubeWall') field.visibleWhen = (p) => p.armStyle === 'tube';
  if (field.key === 'armThickness') field.visibleWhen = (p) => p.armStyle === 'flat';
  if (field.key === 'armAngle')
    field.visibleWhen = (p) => ['quad-x', 'quad-h', 'quad-v', 'octa-x8'].includes(String(p.layout));
}
