import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: 'hinge',
  mountHole: 5,
  hingeWidth: 40,
  hingeLength: 60,
  leafThickness: 3,
  pinDiameter: 5,
  hingeAngle: 0,
  handlePitch: 96,
  handleWidth: 18,
  handleHeight: 32,
  handleThickness: 10,
  handleFootLength: 24,
  latchLength: 80,
  latchWidth: 32,
  boltDiameter: 8,
  latchTravel: 0,
  footDiameter: 40,
  footHeight: 45,
  stemDiameter: 10,
  padThickness: 8,
  capWidth: 40,
  capLength: 40,
  capThickness: 3,
  capInsertion: 10,
  capWall: 2,
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'form',
    label: 'Hardware family',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'hinge', label: 'Five-knuckle hinge' },
      { value: 'handle', label: 'Bridge pull handle' },
      { value: 'latch', label: 'Barrel bolt and strike' },
      { value: 'foot', label: 'Levelling foot' },
      { value: 'cap', label: 'Profile end cap' },
    ],
  },
  {
    key: 'mountHole',
    label: 'Mounting hole diameter',
    type: 'number',
    min: 2,
    max: 15,
    step: 0.1,
    unit: 'mm',
    group: 'Mounting',
    visibleWhen: (p) => ['hinge', 'handle', 'latch'].includes(String(p.form)),
  },
  {
    key: 'hingeWidth',
    label: 'Open hinge width',
    type: 'number',
    min: 24,
    max: 300,
    step: 0.1,
    unit: 'mm',
    group: 'Hinge',
    visibleWhen: (p) => p.form === 'hinge',
  },
  {
    key: 'hingeLength',
    label: 'Hinge length',
    type: 'number',
    min: 24,
    max: 400,
    step: 0.1,
    unit: 'mm',
    group: 'Hinge',
    visibleWhen: (p) => p.form === 'hinge',
  },
  {
    key: 'leafThickness',
    label: 'Leaf thickness',
    type: 'number',
    min: 1,
    max: 12,
    step: 0.1,
    unit: 'mm',
    group: 'Hinge',
    visibleWhen: (p) => p.form === 'hinge',
  },
  {
    key: 'pinDiameter',
    label: 'Hinge pin diameter',
    type: 'number',
    min: 2,
    max: 25,
    step: 0.1,
    unit: 'mm',
    group: 'Hinge',
    visibleWhen: (p) => p.form === 'hinge',
  },
  {
    key: 'hingeAngle',
    label: 'Opening angle',
    type: 'number',
    min: 0,
    max: 150,
    step: 1,
    unit: '\u00b0',
    group: 'Hinge',
    visibleWhen: (p) => p.form === 'hinge',
  },
  {
    key: 'handlePitch',
    label: 'Mounting hole centres',
    type: 'number',
    min: 40,
    max: 400,
    step: 0.1,
    unit: 'mm',
    group: 'Handle',
    visibleWhen: (p) => p.form === 'handle',
  },
  {
    key: 'handleWidth',
    label: 'Foot width',
    type: 'number',
    min: 10,
    max: 60,
    step: 0.1,
    unit: 'mm',
    group: 'Handle',
    visibleWhen: (p) => p.form === 'handle',
  },
  {
    key: 'handleHeight',
    label: 'Overall handle height',
    type: 'number',
    min: 15,
    max: 100,
    step: 0.1,
    unit: 'mm',
    group: 'Handle',
    visibleWhen: (p) => p.form === 'handle',
  },
  {
    key: 'handleThickness',
    label: 'Grip / leg thickness',
    type: 'number',
    min: 6,
    max: 30,
    step: 0.1,
    unit: 'mm',
    group: 'Handle',
    visibleWhen: (p) => p.form === 'handle',
  },
  {
    key: 'handleFootLength',
    label: 'Mounting foot length',
    type: 'number',
    min: 12,
    max: 60,
    step: 0.1,
    unit: 'mm',
    group: 'Handle',
    visibleWhen: (p) => p.form === 'handle',
  },
  {
    key: 'latchLength',
    label: 'Bolt plate length',
    type: 'number',
    min: 50,
    max: 250,
    step: 0.1,
    unit: 'mm',
    group: 'Latch',
    visibleWhen: (p) => p.form === 'latch',
  },
  {
    key: 'latchWidth',
    label: 'Bolt plate width',
    type: 'number',
    min: 20,
    max: 80,
    step: 0.1,
    unit: 'mm',
    group: 'Latch',
    visibleWhen: (p) => p.form === 'latch',
  },
  {
    key: 'boltDiameter',
    label: 'Sliding bolt diameter',
    type: 'number',
    min: 4,
    max: 20,
    step: 0.1,
    unit: 'mm',
    group: 'Latch',
    visibleWhen: (p) => p.form === 'latch',
  },
  {
    key: 'latchTravel',
    label: 'Bolt retraction',
    type: 'number',
    min: 0,
    max: 45,
    step: 0.1,
    unit: 'mm',
    group: 'Latch',
    visibleWhen: (p) => p.form === 'latch',
  },
  {
    key: 'footDiameter',
    label: 'Pad diameter',
    type: 'number',
    min: 20,
    max: 160,
    step: 0.1,
    unit: 'mm',
    group: 'Levelling foot',
    visibleWhen: (p) => p.form === 'foot',
  },
  {
    key: 'footHeight',
    label: 'Overall foot height',
    type: 'number',
    min: 20,
    max: 200,
    step: 0.1,
    unit: 'mm',
    group: 'Levelling foot',
    visibleWhen: (p) => p.form === 'foot',
  },
  {
    key: 'stemDiameter',
    label: 'Stem nominal diameter',
    type: 'number',
    min: 6,
    max: 30,
    step: 0.1,
    unit: 'mm',
    group: 'Levelling foot',
    visibleWhen: (p) => p.form === 'foot',
  },
  {
    key: 'padThickness',
    label: 'Pad thickness',
    type: 'number',
    min: 4,
    max: 30,
    step: 0.1,
    unit: 'mm',
    group: 'Levelling foot',
    visibleWhen: (p) => p.form === 'foot',
  },
  {
    key: 'capWidth',
    label: 'Profile outer width',
    type: 'number',
    min: 15,
    max: 150,
    step: 0.1,
    unit: 'mm',
    group: 'End cap',
    visibleWhen: (p) => p.form === 'cap',
  },
  {
    key: 'capLength',
    label: 'Profile outer length',
    type: 'number',
    min: 15,
    max: 150,
    step: 0.1,
    unit: 'mm',
    group: 'End cap',
    visibleWhen: (p) => p.form === 'cap',
  },
  {
    key: 'capThickness',
    label: 'Cap face thickness',
    type: 'number',
    min: 1,
    max: 8,
    step: 0.1,
    unit: 'mm',
    group: 'End cap',
    visibleWhen: (p) => p.form === 'cap',
  },
  {
    key: 'capInsertion',
    label: 'Insertion depth',
    type: 'number',
    min: 3,
    max: 30,
    step: 0.1,
    unit: 'mm',
    group: 'End cap',
    visibleWhen: (p) => p.form === 'cap',
  },
  {
    key: 'capWall',
    label: 'Skirt wall thickness',
    type: 'number',
    min: 1,
    max: 6,
    step: 0.1,
    unit: 'mm',
    group: 'End cap',
    visibleWhen: (p) => p.form === 'cap',
  },
];
