import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: 'round',
  bore: 25,
  rod: 10,
  stroke: 100,
  extension: 50,
  wall: 3,
  port: 5,
  detail: 'envelope',
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'form',
    label: 'Cylinder form',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'round', label: 'Round pneumatic cylinder' },
      { value: 'tie', label: 'Tie-rod pneumatic cylinder' },
      { value: 'compact', label: 'Compact cylinder' },
      { value: 'hydraulic', label: 'Hydraulic cylinder' },
      { value: 'rodless', label: 'Rodless cylinder' },
    ],
  },
  {
    key: 'bore',
    label: 'Cylinder bore',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'rod',
    label: 'Rod diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'stroke',
    label: 'Rated geometric stroke',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'extension',
    label: 'Rod extension',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 1000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'wall',
    label: 'Tube wall thickness',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'port',
    label: 'Port nominal diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'detail',
    label: 'Model detail',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'envelope', label: 'Envelope \u00b7 assembly fit' },
      { value: 'detailed', label: 'Detailed \u00b7 visible construction' },
    ],
  },
];
