import type { ParameterDefinition, Parameters, PartDefinition } from '../../core/types';
export const defaults: Parameters = {
  length: 500,
  diameter: 40,
  wall: 1,
  noseLength: 100,
  nose: 'elliptical',
  finCount: 4,
  finRoot: 90,
  finTip: 40,
  finSpan: 45,
  finSweep: 15,
  finThickness: 2,
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'length',
    label: 'Overall length',
    type: 'number',
    group: 'Dimensions',
    min: 100,
    max: 2500,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'diameter',
    label: 'Body outside diameter',
    type: 'number',
    group: 'Dimensions',
    min: 15,
    max: 200,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'wall',
    label: 'Tube and nose wall',
    type: 'number',
    group: 'Construction',
    min: 0.3,
    max: 8,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'noseLength',
    label: 'Nose length',
    type: 'number',
    group: 'Dimensions',
    min: 20,
    max: 600,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'nose',
    label: 'Nose profile',
    type: 'select',
    group: 'Construction',
    options: [
      { value: 'elliptical', label: 'Elliptical' },
      { value: 'conical', label: 'Conical' },
    ],
  },
  {
    key: 'finCount',
    label: 'Fin count',
    type: 'number',
    group: 'Fins',
    min: 3,
    max: 6,
    step: 1,
    unit: 'pcs',
  },
  {
    key: 'finRoot',
    label: 'Fin root chord',
    type: 'number',
    group: 'Fins',
    min: 10,
    max: 400,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'finTip',
    label: 'Fin tip chord',
    type: 'number',
    group: 'Fins',
    min: 5,
    max: 300,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'finSpan',
    label: 'Fin radial span',
    type: 'number',
    group: 'Fins',
    min: 5,
    max: 200,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'finSweep',
    label: 'Fin tip offset from base',
    type: 'number',
    group: 'Fins',
    min: 0,
    max: 200,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'finThickness',
    label: 'Fin thickness',
    type: 'number',
    group: 'Fins',
    min: 0.5,
    max: 10,
    step: 0.1,
    unit: 'mm',
  },
];
export const catalogSelection: NonNullable<PartDefinition['catalogSelection']> = [];
