import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: 'duct',
  width: 25,
  height: 18,
  length: 150,
  wall: 2,
  links: 8,
  detail: 'envelope',
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'form',
    label: 'Carrier form',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'duct', label: 'Cable duct' },
      { value: 'chain', label: 'Drag chain' },
    ],
  },
  {
    key: 'width',
    label: 'Outside width',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'height',
    label: 'Outside height',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'length',
    label: 'Length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'wall',
    label: 'Wall thickness',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'links',
    visibleWhen: (p) => p.form === 'chain',
    label: 'Link count',
    type: 'number',
    group: 'Dimensions',
    min: 2,
    max: 30,
    step: 1,
    unit: '',
  },
  {
    key: 'detail',
    visibleWhen: (p) => p.form === 'chain',
    label: 'Model detail',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'envelope', label: 'Envelope \u00b7 assembly fit' },
      { value: 'detailed', label: 'Detailed \u00b7 visible construction' },
    ],
  },
];
