import type { Parameters, ParameterDefinition } from '../../core/types';
import models from './lib/models.json';
export const defaults: Parameters = { model: 'AM08202R015001' };
export const parameters: ParameterDefinition[] = [
  {
    key: 'model',
    label: 'Manufacturer model',
    type: 'select',
    group: 'Catalogue',
    options: models.map((m) => ({ value: m.model, label: m.model })),
  },
];
export const catalogFilterFields: ParameterDefinition[] = [
  {
    key: 'bodyDiameter',
    label: 'Body diameter',
    unit: 'mm',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 100000,
    step: 0.001,
    catalogSummary: true,
  },
  {
    key: 'bodyLength',
    label: 'Body length',
    unit: 'mm',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 100000,
    step: 0.001,
    catalogSummary: true,
  },
  {
    key: 'shaftDiameter',
    label: 'Shaft diameter',
    unit: 'mm',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 100000,
    step: 0.001,
    catalogSummary: false,
  },
  {
    key: 'shaftProjection',
    label: 'Front shaft projection',
    unit: 'mm',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 100000,
    step: 0.001,
    catalogSummary: false,
  },
  {
    key: 'phaseCurrent',
    label: 'Nominal current per phase',
    unit: 'A',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 100000,
    step: 0.001,
    catalogSummary: true,
  },
  {
    key: 'phaseVoltage',
    label: 'Nominal voltage per phase',
    unit: 'V',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 100000,
    step: 0.001,
    catalogSummary: false,
  },
  {
    key: 'phaseResistance',
    label: 'Phase resistance',
    unit: '\u03a9',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 100000,
    step: 0.001,
    catalogSummary: false,
  },
  {
    key: 'phaseInductance',
    label: 'Phase inductance at 1 kHz',
    unit: 'mH',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 100000,
    step: 0.001,
    catalogSummary: false,
  },
  {
    key: 'holdingTorque',
    label: 'Holding torque \u00b7 nominal current',
    unit: 'mNm',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 100000,
    step: 0.001,
    catalogSummary: true,
  },
  {
    key: 'boostedTorque',
    label: 'Holding torque \u00b7 boosted current',
    unit: 'mNm',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 100000,
    step: 0.001,
    catalogSummary: false,
  },
  {
    key: 'stepAngle',
    label: 'Full-step angle',
    unit: '\u00b0',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 100000,
    step: 0.001,
    catalogSummary: false,
  },
];
