import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = { diameter: 4.8, length: 12, head: 9, mandrel: 2.4, pull: 25 };
export const parameters: ParameterDefinition[] = [
  {
    key: 'diameter',
    label: 'Sleeve diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'length',
    label: 'Sleeve length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'head',
    label: 'Head diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'mandrel',
    label: 'Mandrel diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'pull',
    label: 'Exposed mandrel length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
];
