import type { ParameterDefinition } from '../../../core/types';

export const catalogFilterFields: ParameterDefinition[] = [
  {
    key: 'caseLength',
    label: 'Case length',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 1000,
    step: 0.1,
    catalogSummary: true,
  },
  {
    key: 'caseWidth',
    label: 'Case width',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 1000,
    step: 0.1,
    catalogSummary: true,
  },
  {
    key: 'caseHeight',
    label: 'Case height',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 1000,
    step: 0.1,
    catalogSummary: true,
  },
  {
    key: 'totalHeight',
    label: 'Height with output shaft',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 1000,
    step: 0.1,
  },
  {
    key: 'mountPitch',
    label: 'Longitudinal mounting pitch',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 1000,
    step: 0.1,
  },
  {
    key: 'voltageMin',
    label: 'Minimum supply voltage',
    unit: 'V',
    type: 'number',
    group: 'Electrical performance',
    min: 0,
    max: 1000,
    step: 0.1,
  },
  {
    key: 'voltageMax',
    label: 'Maximum supply voltage',
    unit: 'V',
    type: 'number',
    group: 'Electrical performance',
    min: 0,
    max: 1000,
    step: 0.1,
  },
  {
    key: 'referenceVoltage',
    label: 'Torque / speed test voltage',
    unit: 'V',
    type: 'number',
    group: 'Electrical performance',
    min: 0,
    max: 1000,
    step: 0.1,
    catalogCondition: true,
  },
  {
    key: 'stallTorque',
    label: 'Published torque',
    unit: 'kgf·cm',
    type: 'number',
    group: 'Electrical performance',
    min: 0,
    max: 1000,
    step: 0.1,
    catalogSummary: true,
    description:
      'At the listed torque / speed test voltage. Published torque is not a guaranteed continuous rating.',
  },
  {
    key: 'noLoadSpeed',
    label: 'No-load speed',
    unit: 's/60°',
    type: 'number',
    group: 'Electrical performance',
    min: 0,
    max: 1000,
    step: 0.001,
    description: 'Unloaded rotation time at the listed torque / speed test voltage.',
  },
  {
    key: 'noLoadCurrent',
    label: 'Published no-load current',
    unit: 'A',
    type: 'number',
    group: 'Electrical performance',
    min: 0,
    max: 1000,
    step: 0.001,
    catalogSummary: true,
    description:
      'At the source test voltage when specified; see current conditions. Missing ratings stay unknown and do not match a numeric filter.',
  },
  {
    key: 'stallCurrent',
    label: 'Published stall current',
    unit: 'A',
    type: 'number',
    group: 'Electrical performance',
    min: 0,
    max: 1000,
    step: 0.001,
    catalogSummary: true,
    description:
      'At the source test voltage when specified; see current conditions. Missing ratings stay unknown and do not match a numeric filter.',
  },
  {
    key: 'weight',
    label: 'Published weight',
    unit: 'g',
    type: 'number',
    group: 'Construction',
    min: 0,
    max: 1000,
    step: 0.1,
  },
  {
    key: 'splineTeeth',
    label: 'Output spline teeth',
    unit: 'T',
    type: 'number',
    group: 'Construction',
    min: 0,
    max: 1000,
    step: 1,
  },
  {
    key: 'motorType',
    label: 'Motor type',
    type: 'select',
    group: 'Construction',
    options: [
      {
        value: 'Brushless',
        label: 'Brushless',
      },
      {
        value: 'Coreless DC',
        label: 'Coreless DC',
      },
    ],
  },
  {
    key: 'interfaceType',
    label: 'Control interface',
    type: 'select',
    group: 'Construction',
    options: [
      {
        value: 'PWM',
        label: 'PWM',
      },
      {
        value: 'TTL serial bus',
        label: 'TTL serial bus',
      },
    ],
  },
];
