import { mechanismOptions, rotating, jaynesHinged } from './lib/kinematics';
import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  mechanism: 'spiral',
  flapLength: 30,
  tubeOD: 80,
  tubeID: 76,
  height: 96,
  stroke: 8,
  deployment: 50,
  sweep: 60,
  bladeWidth: 22,
  fitClearance: 0.5,
  servo: 'micro',
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'mechanism',
    label: 'Airbrake mechanism',
    type: 'select',
    group: 'Mechanism',
    options: mechanismOptions,
  },
  {
    key: 'tubeOD',
    label: 'Tube outside diameter',
    type: 'number',
    group: 'Housing',
    min: 80,
    max: 180,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'tubeID',
    label: 'Tube inside diameter',
    type: 'number',
    group: 'Housing',
    min: 76,
    max: 176,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'height',
    label: 'Module height',
    type: 'number',
    group: 'Housing',
    min: 80,
    max: 180,
    step: 1,
    unit: 'mm',
  },
  {
    key: 'fitClearance',
    label: 'Radial insert clearance',
    type: 'number',
    group: 'Housing',
    min: 0.2,
    max: 1,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'deployment',
    label: 'Airbrake deployment',
    type: 'number',
    group: 'Motion',
    min: 0,
    max: 100,
    step: 1,
    unit: '%',
    description:
      'Actuates the selected drive from fully retracted (0%) to deployed (100%). Linkage travel is nonlinear; geared petals pivot.',
  },
  {
    key: 'stroke',
    visibleWhen: (p) => !rotating(p),
    label: 'Blade radial travel',
    type: 'number',
    group: 'Mechanism',
    min: 4,
    max: 30,
    step: 0.5,
    unit: 'mm',
  },
  {
    key: 'sweep',
    label: 'Servo travel for full deployment',
    type: 'number',
    group: 'Mechanism',
    min: 45,
    max: 90,
    step: 1,
    unit: '°',
  },
  {
    key: 'bladeWidth',
    visibleWhen: (p) => jaynesHinged(p) || !rotating(p),
    label: 'Blade tangential width',
    type: 'number',
    group: 'Mechanism',
    min: 16,
    max: 36,
    step: 1,
    unit: 'mm',
  },
  {
    key: 'flapLength',
    label: 'Hinged flap length',
    type: 'number',
    group: 'Mechanism',
    min: 20,
    max: 60,
    step: 1,
    unit: 'mm',
    visibleWhen: jaynesHinged,
  },
  {
    key: 'servo',
    label: 'Servo installation size',
    type: 'select',
    group: 'Drive',
    options: [
      { value: 'standard', label: 'Standard · 40.7 × 19.7 × 42.9 mm' },
      { value: 'micro', label: 'Micro · 22.8 × 12.2 × 28.5 mm' },
    ],
    description:
      'MG996R / MG90S body-size references. Mounts and drive adaptor are reconstructed; no load rating is implied.',
  },
];
