import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  diameter: 70,
  centres: 180,
  width: 35,
  thickness: 5,
  bore: 10,
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'diameter',
    label: 'Wheel diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'centres',
    label: 'Wheel centre distance',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'width',
    label: 'Track width',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'thickness',
    label: 'Track thickness',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'bore',
    label: 'Axle bore',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
];
