import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  diameter: 30,
  bodyLength: 180,
  rod: 12,
  stroke: 100,
  extension: 50,
  motor: 40,
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'diameter',
    label: 'Tube diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'bodyLength',
    label: 'Tube length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'rod',
    label: 'Rod diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'stroke',
    description:
      'Maximum travel limit. Change extension to move the mechanism; changing this limit alone preserves its current position.',
    label: 'Stroke',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'extension',
    label: 'Extension',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 1000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'motor',
    label: 'Motor housing width',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
];
