import type { ParameterDefinition, Parameters, PartDefinition } from '../../core/types';
import models from './lib/models.json';
export const defaults: Parameters = { model: '17hs19-2004s1', outputAngle: 0, showLeads: false };
export const parameters: ParameterDefinition[] = [
  {
    key: 'model',
    label: 'Motor model',
    type: 'select',
    group: 'Model',
    options: models.map((m) => ({ value: m.id, label: m.name })),
    description: 'Fixed supplier dimensions. Select a model using catalog filters.',
  },
  {
    key: 'outputAngle',
    label: 'Shaft position',
    unit: '°',
    type: 'number',
    group: 'Assembly',
    min: -180,
    max: 180,
    step: 1,
    filterable: false,
    description: 'Geometric rotor position only.',
  },
  {
    key: 'showLeads',
    label: 'Show short cable leads',
    type: 'boolean',
    group: 'Assembly',
    filterable: false,
    description:
      'Illustrative straight leads for clearance planning; actual cable routing and length vary.',
  },
];
export const catalogSelection: NonNullable<PartDefinition['catalogSelection']> = [{ key: 'model' }];
export const catalogFilterFields: ParameterDefinition[] = [
  {
    key: 'width',
    label: 'Frame width',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 150,
    step: 0.1,
    catalogSummary: true,
  },
  {
    key: 'length',
    label: 'Body length',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 300,
    step: 0.1,
    catalogSummary: true,
  },
  {
    key: 'shaft',
    label: 'Shaft diameter',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 30,
    step: 0.1,
    catalogSummary: true,
  },
  {
    key: 'extension',
    label: 'Shaft extension',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 100,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'pilot',
    label: 'Locating pilot',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 100,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'pitch',
    label: 'Square mounting pitch',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 120,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'torque',
    label: 'Holding torque',
    unit: 'N\u00b7m',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 50,
    step: 0.001,
    catalogSummary: true,
  },
  {
    key: 'current',
    label: 'Rated phase current',
    unit: 'A',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 20,
    step: 0.1,
    catalogSummary: true,
  },
  {
    key: 'weight',
    label: 'Mass',
    unit: 'g',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 15000,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'resistance',
    label: 'Phase resistance',
    unit: '\u03a9',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 50,
    step: 0.001,
    catalogSummary: false,
  },
  {
    key: 'inductance',
    label: 'Phase inductance',
    unit: 'mH',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 50,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'nema',
    label: 'NEMA frame',
    type: 'select',
    group: 'Model',
    options: [
      {
        value: '8',
        label: 'NEMA 8',
      },
      {
        value: '11',
        label: 'NEMA 11',
      },
      {
        value: '14',
        label: 'NEMA 14',
      },
      {
        value: '17',
        label: 'NEMA 17',
      },
      {
        value: '23',
        label: 'NEMA 23',
      },
      {
        value: '24',
        label: 'NEMA 24',
      },
      {
        value: '34',
        label: 'NEMA 34',
      },
      {
        value: '42',
        label: 'NEMA 42',
      },
    ],
    catalogSummary: true,
  },
  {
    key: 'winding',
    label: 'Winding',
    type: 'select',
    group: 'Model',
    options: [
      {
        value: 'unipolar',
        label: 'Unipolar',
      },
      {
        value: 'bipolar',
        label: 'Bipolar',
      },
    ],
    catalogSummary: true,
  },
  {
    key: 'shaftType',
    label: 'Shaft type',
    type: 'select',
    group: 'Model',
    options: [
      {
        value: 'D',
        label: 'D',
      },
      {
        value: 'round',
        label: 'Round',
      },
      {
        value: 'keyed',
        label: 'Keyed',
      },
    ],
    catalogSummary: true,
  },
];
