import type { Parameters, Preset } from '../core/types';

// Dimensions were transcribed from individual live product tables, not category filters.
// Fields absent from verifiedParameters are representative geometry choices.
function product(
  id: string,
  designation: string,
  parameters: Parameters,
  path: string,
  verifiedParameters: string[],
  manufacturer?: string,
  description = 'Verified supplier dimensions; internal geometry is representative.',
): Preset {
  return {
    id,
    name: `${designation}${manufacturer ? ` · ${manufacturer}` : ''}`,
    description,
    parameters,
    catalog: {
      designation,
      manufacturer,
      sourceName: 'Promtehimport',
      sourceUrl: `https://promtehimport.com.ua/offer/${path}/`,
      verifiedParameters,
    },
  };
}
const envelope = ['bore', 'outer', 'width'];

export const motionBearingCatalog: Record<string, Preset[]> = {
  'linear-bearing': [
    product(
      'lm8uu',
      'LM08 UU',
      { bore: 8, outer: 15, width: 24 },
      'liniyiniyi-pidshipnik-lm-08-uu-fo-bearings-o7761',
      envelope,
      'FO Bearings',
      '8 × 15 × 24 mm',
    ),
    product(
      'lm12uu',
      'LM12 UU',
      { bore: 12, outer: 21, width: 30 },
      'liniyiniyi-pidshipnik-lm12-uu-fo-bearings-o1520',
      envelope,
      'FO Bearings',
      '12 × 21 × 30 mm',
    ),
  ],
  'thrust-bearing': [
    product(
      'small',
      '51100 / 8100',
      { bore: 10, outer: 24, width: 9, balls: 8 },
      'pidshipnik-51100-8100-10x24x9-fo-bearings-o3473',
      envelope,
      'FO Bearings',
      '10 × 24 × 9 mm; ball count is illustrative',
    ),
    product(
      'medium',
      '51104 / 8104',
      { bore: 20, outer: 35, width: 10, balls: 10 },
      'pidshipnik-51104-8104-20x35x10-o1314',
      envelope,
      undefined,
      '20 × 35 × 10 mm; supplier brand field is unspecified',
    ),
  ],
  'rod-end-bearing': [
    product(
      'sa08-ct',
      'SA08-T/K',
      { bore: 8, outer: 24, width: 12, headWidth: 9, stemDiameter: 8, stemLength: 30 },
      'sharnirna-golovka-sa08-t-k-ct-o9051',
      ['bore', 'outer', 'width', 'headWidth', 'stemDiameter'],
      'CT',
      '8 mm bore; 24 mm eye; M8 shank envelope. Extension derived from h − d2/2.',
    ),
    product(
      'sa10-ct',
      'SA10-T/K',
      { bore: 10, outer: 28, width: 14, headWidth: 10.5, stemDiameter: 10, stemLength: 34 },
      'sharnirna-golovka-sa10-t-k-ct-o1519',
      ['bore', 'outer', 'width', 'headWidth', 'stemDiameter'],
      'CT',
      '10 mm bore; 28 mm eye; M10 shank envelope. Extension derived from h − d2/2.',
    ),
  ],
  'pillow-block-bearing': [
    product(
      'ucp204',
      'UCP204',
      {
        bore: 20,
        outer: 63.4,
        width: 24,
        insertWidth: 31,
        totalHeight: 65,
        centerHeight: 33.3,
        baseWidth: 127,
        baseDepth: 38,
        baseThickness: 8,
        hole: 12,
        slotLength: 16,
        mountPitch: 95,
      },
      'pidshipnik-korpusniyi-ucp204-o1116',
      [
        'bore',
        'insertWidth',
        'totalHeight',
        'centerHeight',
        'baseWidth',
        'baseDepth',
        'mountPitch',
      ],
      undefined,
      '20 mm shaft; 127 × 38 × 65 mm envelope; 95 mm mounting centers. Crown and base thickness are representative.',
    ),
    product(
      'ucp205-fo',
      'UCP205',
      {
        bore: 25,
        outer: 69,
        width: 26,
        insertWidth: 34.1,
        totalHeight: 71,
        centerHeight: 36.5,
        baseWidth: 140,
        baseDepth: 38,
        baseThickness: 8,
        hole: 13,
        slotLength: 19,
        mountPitch: 105,
      },
      'pidshipnik-korpusniyi-ucp205-fo-bearings-o1115',
      [
        'bore',
        'insertWidth',
        'totalHeight',
        'centerHeight',
        'baseWidth',
        'baseDepth',
        'mountPitch',
        'hole',
        'slotLength',
      ],
      'FO Bearings',
      '25 mm shaft; 140 × 38 × 71 mm envelope; 105 mm centers and 13 × 19 mm slots. Base thickness is representative.',
    ),
  ],
  'insert-bearing': [
    product(
      'uc204-fo',
      'UC204 / 480204',
      { bore: 20, outer: 47, width: 31, outerWidth: 17, hubDiameter: 27.56 },
      'zakriplyuvalniyi-pidshipnik-uc204-480204-fo-bearings-o11031',
      [...envelope, 'outerWidth', 'hubDiameter'],
      'FO Bearings',
      '20 × 47 × 31 mm; 17 mm outer ring; 27.56 mm inner shoulder',
    ),
    product(
      'uc205',
      'UC205 / 480205',
      { bore: 25, outer: 52, width: 34, outerWidth: 17, hubDiameter: 33 },
      'pidshipnikuc-205-480205-o1231',
      [...envelope, 'outerWidth'],
      undefined,
      '25 × 52 × 34 mm; 17 mm outer ring; hub shoulder is representative',
    ),
  ],
  'one-way-clutch': [
    product(
      'hf1012-cx',
      'HF1012',
      { bore: 10, outer: 14, width: 12, rollers: 10 },
      'obginna-mufta-hf1012-cx-poland-o10714',
      envelope,
      'CX',
      '10 × 14 × 12 mm drawn-cup clutch; roller count is illustrative',
    ),
    product(
      'hf1216-cx',
      'HF1216',
      { bore: 12, outer: 18, width: 16, rollers: 12 },
      'obginna-mufta-hf1216-cx-poland-o10713',
      envelope,
      'CX',
      '12 × 18 × 16 mm drawn-cup clutch; roller count is illustrative',
    ),
  ],
  'thrust-roller-bearing': [
    product(
      '81105m-fo',
      '81105M / 9105',
      { bore: 25, outer: 42, width: 11, washer: 3, rollers: 12 },
      'pidshipnik-81105m-9105l-fo-bearings-25x42x11-o12308',
      [...envelope, 'washer'],
      'FO Bearings',
      '25 × 42 × 11 mm; 3 mm shaft washer',
    ),
    product(
      '81110m',
      '81110M / 9110',
      { bore: 50, outer: 70, width: 14, washer: 4, rollers: 18 },
      'pidshipnik-81110-m-9110l-fo-bearings-o9059',
      [...envelope, 'washer'],
      undefined,
      '50 × 70 × 14 mm; 4 mm shaft washer; supplier brand field is unspecified',
    ),
  ],
  'combined-bearing': [
    product(
      'nkib5903-zsg',
      'NKIB5903',
      { bore: 17, outer: 30, width: 20, outerWidth: 18, raceDiameter: 22, rollers: 16, balls: 10 },
      'pidshipnik-nkib5903-zsg-o7391',
      [...envelope, 'outerWidth', 'raceDiameter'],
      'ZSG',
      '17 × 30 × 20 mm; C = 18 mm; F = 22 mm',
    ),
    product(
      'nkib5904-zsg',
      'NKIB5904',
      { bore: 20, outer: 37, width: 25, outerWidth: 23, raceDiameter: 25, rollers: 18, balls: 10 },
      'pidshipnik-nkib5904-zsg-o7392',
      [...envelope, 'outerWidth', 'raceDiameter'],
      'ZSG',
      '20 × 37 × 25 mm; C = 23 mm; F = 25 mm',
    ),
  ],
  'plain-bearing': [
    product(
      'ge08-e-fo',
      'GE08-E / ShSP8',
      { bore: 8, outer: 16, width: 8, outerWidth: 5 },
      'pidshipnik-sharnirniyi-ge08-e-shsp8-fo-bearings-o9062',
      [...envelope, 'outerWidth'],
      'FO Bearings',
      '8 × 16 × 8 mm spherical plain bearing; 5 mm outer ring',
    ),
    product(
      'ge20-es-fo',
      'GE20-ES / ShSP20',
      { bore: 20, outer: 35, width: 16, outerWidth: 12 },
      'sharnirniyi-pidshipnik-ge-20-es-shsp20-fo-bearings-o1369',
      [...envelope, 'outerWidth'],
      'FO Bearings',
      '20 × 35 × 16 mm spherical plain bearing; 12 mm outer ring',
    ),
  ],
  'adapter-sleeve': [
    product(
      'h206',
      'H206',
      { bore: 25, outer: 45, width: 27, seatDiameter: 30, nutThickness: 7, slitAngle: 4 },
      'zakriplyuvalna-vtulka-h-206-o5119',
      [...envelope, 'seatDiameter', 'nutThickness'],
      undefined,
      '25 mm shaft; 30 mm seat; 45 mm locknut; 27 mm assembly length',
    ),
    product(
      'h208',
      'H208',
      { bore: 35, outer: 58, width: 31, seatDiameter: 40, nutThickness: 9, slitAngle: 4 },
      'zakriplyuvalna-vtulka-h-208-o5117',
      [...envelope, 'seatDiameter', 'nutThickness'],
      undefined,
      '35 mm shaft; 40 mm seat; 58 mm locknut; 31 mm assembly length',
    ),
  ],
  'radial-oil-seal': [
    product(
      '14-28-7-cx',
      '14 × 28 × 7',
      { bore: 14, outer: 28, width: 7 },
      'salnik-manjeta-armovana-14-28-7-cx-polscha-o11706',
      envelope,
      'CX',
      '14 mm shaft; 28 mm housing bore; 7 mm width',
    ),
    product(
      '20-40-7-cx',
      '20 × 40 × 7',
      { bore: 20, outer: 40, width: 7 },
      'salnik-manjeta-armovana-20-40-7-cx-polscha-o11721',
      envelope,
      'CX',
      '20 mm shaft; 40 mm housing bore; 7 mm width',
    ),
  ],
};

export function motionSources(id: string) {
  return motionBearingCatalog[id].map((preset) => ({
    label: `${preset.catalog!.sourceName} · ${preset.catalog!.designation}`,
    url: preset.catalog!.sourceUrl,
  }));
}
