import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: 'button',
  diameter: 28,
  mount: 22,
  height: 12,
  depth: 25,
  segments: 3,
  detail: 'envelope',
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'form',
    label: 'Control type',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'button', label: 'Pushbutton' },
      { value: 'knob', label: 'Rotary knob' },
      { value: 'beacon', label: 'Signal tower' },
    ],
  },
  {
    key: 'diameter',
    label: 'Head diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'mount',
    label: 'Panel opening diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'height',
    label: 'Head height',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'depth',
    label: 'Rear body depth',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'segments',
    label: 'Beacon lens segments',
    type: 'number',
    group: 'Dimensions',
    min: 1,
    max: 5,
    step: 1,
    unit: '',
  },
  {
    key: 'detail',
    label: 'Model detail',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'envelope', label: 'Envelope \u00b7 assembly fit' },
      { value: 'detailed', label: 'Detailed \u00b7 visible construction' },
    ],
  },
];
