import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: 'dc',
  diameter: 50,
  length: 70,
  shaft: 8,
  projection: 20,
  pitch: 35,
  hole: 4,
  detail: 'envelope',
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'form',
    label: 'Motor family',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'dc', label: 'Brushed DC can motor' },
      { value: 'tt', label: 'Geared DC motor' },
      { value: 'iec-b3', label: 'IEC-style foot motor' },
      { value: 'iec-b5', label: 'IEC-style flange motor' },
      { value: 'servo', label: 'Industrial servo' },
      { value: 'torque', label: 'Pancake torque motor' },
    ],
  },
  {
    key: 'diameter',
    label: 'Body diameter / width',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'length',
    label: 'Body length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'shaft',
    label: 'Shaft diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'projection',
    label: 'Shaft projection',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'pitch',
    label: 'Mounting bolt circle',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'hole',
    label: 'Mounting hole diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'detail',
    label: 'Model detail',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'envelope', label: 'Envelope \u00b7 assembly fit' },
      { value: 'detailed', label: 'Detailed \u00b7 visible construction' },
    ],
  },
];
