import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: 'tr',
  diameter: 8,
  length: 250,
  pitch: 2,
  nutLength: 20,
  nutDiameter: 28,
  position: 100,
  turns: 50,
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'turns',
    label: 'Input revolutions from origin',
    type: 'number',
    group: 'Travel',
    min: 0,
    max: 4000,
    step: 0.1,
    unit: 'rev',
    description: 'Nut travel = revolutions × lead. Editing travel updates the input revolutions.',
  },
  {
    key: 'form',
    label: 'Thread system',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'tr', label: 'Metric trapezoidal' },
      { value: 'acme', label: 'ACME' },
    ],
  },
  {
    key: 'diameter',
    label: 'Screw nominal diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'length',
    label: 'Screw length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'pitch',
    description:
      'Changes travel for the current input revolutions. The screw uses a smooth thread envelope; use Thread tool for a helical Boolean solid.',
    label: 'Lead per revolution',
    type: 'number',
    group: 'Dimensions',
    min: 0.5,
    max: 20,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'nutLength',
    label: 'Nut length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'nutDiameter',
    label: 'Nut flange diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'position',
    label: 'Nut position',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
];
