import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  diameter: 20,
  rod: 8,
  bodyLength: 150,
  stroke: 80,
  extension: 40,
  eye: 6,
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'diameter',
    label: 'Body diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'rod',
    label: 'Rod diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'bodyLength',
    label: 'Body length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'stroke',
    label: 'Stroke',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'extension',
    label: 'Extension',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 1000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'eye',
    label: 'Eye bore',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
];
