import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: 'straight',
  connection: 'push',
  diameter: 14,
  passage: 6,
  length: 28,
  connectionDiameter: 10,
  detail: 'detailed',
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'form',
    label: 'Fitting form',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'straight', label: 'Straight union' },
      { value: 'elbow', label: '90-degree elbow' },
      { value: 'tee', label: 'T fitting' },
      { value: 'quick', label: 'Quick coupling' },
      { value: 'bulkhead', label: 'Bulkhead fitting' },
    ],
  },
  {
    key: 'connection',
    description:
      'BSP and metric are nominal thread envelopes: equal entered diameters can produce the same exterior. Helical thread flanks are not represented.',
    label: 'Connection style',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'push', label: 'Push-in tube' },
      { value: 'bsp', label: 'BSP nominal thread' },
      { value: 'metric', label: 'Metric nominal thread' },
      { value: 'jic', label: 'JIC-style cone' },
      { value: 'orfs', label: 'ORFS-style face' },
    ],
  },
  {
    key: 'diameter',
    label: 'Fitting body diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'passage',
    label: 'Flow passage diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'length',
    label: 'Body length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'connectionDiameter',
    label: 'Connection outside diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'detail',
    visibleWhen: (p) => p.connection === 'push',
    label: 'Model detail',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'envelope', label: 'Envelope \u00b7 assembly fit' },
      { value: 'detailed', label: 'Detailed \u00b7 visible construction' },
    ],
  },
];
