import type { ParameterDefinition, Parameters, PartDefinition } from '../../core/types';
import models from './lib/models.json';
export const defaults: Parameters = { model: 'x2814', outputAngle: 0, showLeads: false };
export const parameters: ParameterDefinition[] = [
  {
    key: 'model',
    label: 'Motor model',
    type: 'select',
    group: 'Model',
    options: models.map((m) => ({ value: m.id, label: m.name })),
    description: 'Fixed supplier dimensions. Select a model using catalog filters.',
  },
  {
    key: 'outputAngle',
    label: 'Shaft position',
    unit: '°',
    type: 'number',
    group: 'Assembly',
    min: -180,
    max: 180,
    step: 1,
    filterable: false,
    description: 'Geometric rotor position only.',
  },
  {
    key: 'showLeads',
    label: 'Show short cable leads',
    type: 'boolean',
    group: 'Assembly',
    filterable: false,
    description:
      'Illustrative straight leads for clearance planning; actual cable routing and length vary.',
  },
];
export const catalogSelection: NonNullable<PartDefinition['catalogSelection']> = [{ key: 'model' }];
export const catalogFilterFields: ParameterDefinition[] = [
  {
    key: 'application',
    label: 'Application',
    type: 'select',
    group: 'Model',
    catalogSummary: true,
    options: [
      { value: 'whoop', label: 'Micro whoop' },
      { value: 'micro-fpv', label: 'Micro FPV / cinewhoop' },
      { value: 'fpv', label: '5-inch FPV' },
      { value: 'fpv-long-range', label: '7–8-inch FPV' },
      { value: 'large-fpv', label: 'Large FPV' },
      { value: 'multirotor', label: 'Multirotor' },
      { value: 'large-multirotor', label: 'Large multirotor' },
      { value: 'general-rc', label: 'General RC' },
      { value: 'rc-car', label: 'RC car' },
    ],
    description:
      'Application families; propeller and electrical compatibility depend on the complete setup.',
  },
  {
    key: 'diameter',
    label: 'Body diameter',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 100,
    step: 0.1,
    catalogSummary: true,
  },
  {
    key: 'length',
    label: 'Body length',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 150,
    step: 0.1,
    catalogSummary: true,
  },
  {
    key: 'shaft',
    label: 'Exposed shaft diameter',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 30,
    step: 0.1,
    catalogSummary: true,
  },
  {
    key: 'extension',
    label: 'Shaft extension',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 100,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'kv',
    label: 'Speed constant',
    unit: 'rpm/V',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 30000,
    step: 1,
    catalogSummary: true,
  },
  {
    key: 'current',
    label: 'Max current (limited duration)',
    unit: 'A',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 150,
    step: 0.1,
    catalogSummary: true,
  },
  {
    key: 'power',
    label: 'Published max power',
    unit: 'W',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 5000,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'weight',
    label: 'Mass',
    unit: 'g',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 2000,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'noLoadCurrent',
    label: 'No-load current',
    unit: 'A',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 20,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'resistance',
    label: 'Resistance',
    unit: '\u03a9',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 1,
    step: 0.001,
    catalogSummary: false,
  },
  {
    key: 'cellMin',
    label: 'Minimum LiPo cells',
    unit: 'S',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 12,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'cellMax',
    label: 'Maximum LiPo cells',
    unit: 'S',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 12,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'manufacturer',
    label: 'Manufacturer',
    type: 'select',
    group: 'Model',
    options: [...new Set(models.map((m) => m.manufacturer))].map((value) => ({
      value,
      label: value,
    })),
    catalogSummary: true,
  },
  {
    key: 'rotor',
    label: 'Rotor type',
    type: 'select',
    group: 'Model',
    options: [
      {
        value: 'outrunner',
        label: 'Outrunner',
      },
      {
        value: 'inrunner',
        label: 'Inrunner',
      },
    ],
    catalogSummary: true,
  },
];
