import type { Parameters, ParameterDefinition } from '../../core/types';

export const defaults: Parameters = {
  tubeOD: 90,
  tubeID: 86,
  releaseFitGap: 0.4,
  bayLength: 465,
  aftLayout: 'payload-bay',
  payloadBayLength: 180,
  omittedPayloadMass: 0.5,
  packFrontGap: 10,
  dispenserDiskGap: 15,
  separation: 480,
  avionicsLayout: 'wing-2s',
  cellModel: 'molicel-p28a',
  plateMaterial: 'aluminium',
  plateThickness: 3,
  printFemaleAllowance: 0.15,
  printMaleRelief: 0.1,
  packDiameter: 80,
  packLength: 300,
  pinCount: 3,
  measuredPinForce: 25,
  sealDrag: 10,
  separatingMass: 1,
  axialGravity: 1,
  gasVolume: 1.5,
  temperature: 20,
  recoveredMass: 10,
  openingLoadFactor: 20,
  structuralFactor: 2,
  designG: 50,
  finderWrapThickness: 0.3,
  finderTapeThickness: 0.5,
  wingPitchX: 18,
  wingPitchY: 22,
};
const n = (
  key: string,
  label: string,
  group: string,
  min: number,
  max: number,
  step = 1,
  unit = 'mm',
): ParameterDefinition => ({ key, label, group, type: 'number', min, max, step, unit });
export const parameters: ParameterDefinition[] = [
  { ...n('tubeOD', 'Tube outside diameter', 'Airframe', 90, 90), visibleWhen: () => false },
  { ...n('tubeID', 'Tube inside diameter', 'Airframe', 86, 86), visibleWhen: () => false },
  n('releaseFitGap', 'O-ring release spigot diametral clearance', 'Airframe', 0.2, 0.8, 0.05),
  n('bayLength', 'Parachute bay length', 'Airframe', 300, 600, 5),
  {
    key: 'aftLayout',
    label: 'Behind the parachute bay',
    type: 'select',
    group: 'Airframe',
    options: [
      { value: 'payload-bay', label: 'Computer / camera bay, then motor' },
      { value: 'direct-motor', label: 'Direct motor interface (no lower electronics bay)' },
    ],
  },
  {
    ...n('payloadBayLength', 'Computer / camera bay length', 'Airframe', 180, 350, 5),
    visibleWhen: (p) => p.aftLayout === 'payload-bay',
  },
  n('separation', 'Inspection separation travel', 'Airframe', 360, 800, 10),
  {
    key: 'avionicsLayout',
    label: 'Controller and battery assembly',
    type: 'select',
    group: 'Electronics',
    options: [
      { value: 'wing-2s', label: 'F405 WING-MINI / 2 x 18650 2S' },
      { value: 'wing-4s', label: 'F405 WING-MINI / 4 x 18650 4S' },
      { value: 'h7-4s', label: 'LCH7 v3.2 / 4 x 18650 4S' },
    ],
  },
  {
    key: 'cellModel',
    label: 'Matched 18650 cell model',
    type: 'select',
    group: 'Electronics',
    options: [
      { value: 'molicel-p28a', label: 'Molicel P28A (library)' },
      { value: 'molicel-p30b', label: 'Molicel P30B (library)' },
    ],
  },
  {
    key: 'plateMaterial',
    label: 'Plate manufacturing route',
    type: 'select',
    group: 'Manufacturing',
    options: [
      { value: 'aluminium', label: 'Al6061 round blank: turn, drill and tap' },
      { value: 'steel', label: 'Steel sheet: laser cut, drill, tap and deburr' },
    ],
  },
  n('plateThickness', 'Electronics plate thickness', 'Manufacturing', 2, 4, 1),
  n(
    'printFemaleAllowance',
    'Printed female thread radial allowance',
    'Printed fits',
    0.05,
    0.25,
    0.025,
  ),
  n('printMaleRelief', 'Printed male thread radial relief', 'Printed fits', 0.05, 0.2, 0.025),
  n('finderWrapThickness', 'Nose module heat-shrink wall allowance', 'Electronics', 0, 0.5, 0.1),
  n('finderTapeThickness', 'Nose mounting tape thickness', 'Electronics', 0.2, 1, 0.1),
  n('dispenserDiskGap', 'Dispenser nut to first disk clearance', 'Electronics', 15, 30, 1),
  {
    ...n('wingPitchX', 'FC mounting pitch X (verify hardware)', 'Electronics', 16, 20, 0.5),
    visibleWhen: (p) => p.avionicsLayout === 'wing-2s' || p.avionicsLayout === 'wing-4s',
  },
  {
    ...n('wingPitchY', 'FC mounting pitch Y (verify hardware)', 'Electronics', 20, 24, 0.5),
    visibleWhen: (p) => p.avionicsLayout === 'wing-2s' || p.avionicsLayout === 'wing-4s',
  },
  n('packDiameter', 'Packed drogue + main diameter', 'Parachute', 40, 80),
  n('packLength', 'Packed drogue + main length', 'Parachute', 100, 350, 5),
  n('packFrontGap', 'Packed parachute to cartridge clearance', 'Parachute', 10, 30, 1),
  n('pinCount', 'Nylon M2.5x8 countersunk shear screw count', 'Release calculation', 2, 4, 1, ''),
  n(
    'measuredPinForce',
    'Single screw break force (assumed until measured)',
    'Release calculation',
    5,
    150,
    1,
    'N',
  ),
  n('sealDrag', 'Seal / extraction drag (assumed)', 'Release calculation', 0, 100, 1, 'N'),
  n('separatingMass', 'Separating assembly mass', 'Release calculation', 0.1, 3, 0.1, 'kg'),
  n('axialGravity', 'Adverse axial gravity', 'Release calculation', 0, 1, 0.1, 'g'),
  n(
    'gasVolume',
    'Effective free chamber volume (measure)',
    'Release calculation',
    0.2,
    3,
    0.05,
    'L',
  ),
  n('temperature', 'Gas temperature for ideal-gas screening', 'Release calculation', 0, 40, 1, 'C'),
  n(
    'recoveredMass',
    'Recovered mass including optional lower bay',
    'Load screening',
    8,
    10,
    0.1,
    'kg',
  ),
  {
    ...n(
      'omittedPayloadMass',
      'Mass removed with lower electronics bay',
      'Load screening',
      0,
      2,
      0.1,
      'kg',
    ),
    visibleWhen: (p) => p.aftLayout === 'direct-motor',
  },
  n('openingLoadFactor', 'Peak harness tension / weight (assumed)', 'Load screening', 1, 50, 1, ''),
  n('structuralFactor', 'Structural screening factor (assumed)', 'Load screening', 1, 3, 0.1, ''),
  n('designG', 'Battery retention acceleration (assumed)', 'Load screening', 10, 100, 5, 'g'),
];
