import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  size: 40,
  depth: 10,
  pitch: 32,
  hole: 3.2,
  blades: 7,
  detail: 'envelope',
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'size',
    label: 'Frame size',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'depth',
    label: 'Frame depth',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'pitch',
    label: 'Mounting hole spacing',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'hole',
    label: 'Mounting hole diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'blades',
    label: 'Blade count',
    type: 'number',
    group: 'Dimensions',
    min: 3,
    max: 12,
    step: 1,
    unit: '',
  },
  {
    key: 'detail',
    label: 'Model detail',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'envelope', label: 'Envelope \u00b7 assembly fit' },
      { value: 'detailed', label: 'Detailed \u00b7 visible construction' },
    ],
  },
];
