import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  pitch: 12.7,
  teeth: 16,
  centres: 200,
  width: 12,
  bore: 12,
  detail: 'envelope',
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'pitch',
    label: 'Chain pitch',
    type: 'number',
    group: 'Dimensions',
    min: 3,
    max: 40,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'teeth',
    label: 'Sprocket tooth count',
    type: 'number',
    group: 'Dimensions',
    min: 10,
    max: 50,
    step: 1,
    unit: '',
  },
  {
    key: 'centres',
    label: 'Shaft centre distance',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'width',
    label: 'Chain width',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'bore',
    label: 'Shaft bore',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'detail',
    label: 'Model detail',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'envelope', label: 'Envelope \u00b7 assembly fit' },
      { value: 'detailed', label: 'Detailed \u00b7 visible construction' },
    ],
  },
];
