import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = { cable: 6, thread: 12, hex: 18, length: 22, nut: 8 };
export const parameters: ParameterDefinition[] = [
  {
    key: 'cable',
    label: 'Cable bore',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'thread',
    label: 'Panel thread nominal diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'hex',
    label: 'Hexagon across flats',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'length',
    label: 'Body length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'nut',
    label: 'Compression nut height',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
];
