import type { ParameterDefinition, Parameters } from '../../core/types';

export const defaults: Parameters = {
  profile: 'round',
  width: 120,
  height: 80,
  wall: 4,
  cutLength: 50,
  stockLength: 2000,
  kerf: 1.5,
  pressure: 6,
  liftPressure: 6,
  headMass: 40,
  feedResistance: 30,
  cuttingForce: 60,
  friction: 0.25,
  stopWindow: 0.05,
  axisDrift: 0.05,
  gripAllowance: 0.05,
  strokePosition: 50,
  carriagePosition: 0,
  shelfPosition: 0,
  showGuards: true,
};
const field = (
  key: string,
  label: string,
  unit: string,
  min: number,
  max: number,
  step: number,
  group: string,
  description?: string,
): ParameterDefinition => ({
  key,
  label,
  type: 'number',
  unit,
  min,
  max,
  step,
  group,
  description,
});
export const parameters: ParameterDefinition[] = [
  {
    key: 'profile',
    label: 'Stock section',
    type: 'select',
    group: 'Stock',
    options: [
      { value: 'round', label: 'Round tube' },
      { value: 'square', label: 'Square tube' },
      { value: 'rectangular', label: 'Rectangular tube' },
      { value: 'triangular', label: 'Triangular tube · apex up' },
      { value: 'oval', label: 'Oval tube' },
    ],
  },
  field('width', 'Tube diameter / section width', 'mm', 30, 120, 1, 'Stock'),
  {
    ...field('height', 'Section height', 'mm', 30, 120, 1, 'Stock'),
    visibleWhen: (p) => !['round', 'square'].includes(String(p.profile)),
  },
  field('wall', 'Wall thickness', 'mm', 1, 6, 0.1, 'Stock'),
  field('stockLength', 'Operator-loaded bar length', 'mm', 1000, 2000, 100, 'Stock'),
  field('cutLength', 'Finished part length', 'mm', 30, 100, 1, 'Cutting'),
  field(
    'kerf',
    'Measured tooth-set kerf',
    'mm',
    1.1,
    2.5,
    0.1,
    'Cutting',
    'Calibrate from real cuts. Feed increment is finished length plus kerf.',
  ),
  field('stopWindow', 'Axis travel stop window', 'mm', 0.05, 0.15, 0.01, 'Accuracy'),
  field('axisDrift', 'Maximum axis movement during hold', 'mm', 0.025, 0.15, 0.025, 'Accuracy'),
  field(
    'gripAllowance',
    'Unmeasured grip error allowance',
    'mm',
    0.025,
    0.15,
    0.025,
    'Accuracy',
    'Planning allowance requiring cut trials; motor encoder cannot measure stock slip.',
  ),
  field('pressure', 'Gripper and vise regulator', 'bar', 3, 7, 0.1, 'Force checks'),
  field('liftPressure', 'Head lift regulator', 'bar', 4, 7, 0.1, 'Force checks'),
  field('headMass', 'Moving head mass allowance', 'kg', 20, 100, 1, 'Force checks'),
  field('friction', 'Measured jaw friction assumption', '', 0.15, 0.4, 0.01, 'Force checks'),
  field('feedResistance', 'Stock feed resistance allowance', 'N', 10, 80, 5, 'Force checks'),
  field('cuttingForce', 'Axial holding load allowance', 'N', 20, 150, 5, 'Force checks'),
  field('strokePosition', 'Head downstroke inspection', '%', 0, 100, 5, 'Preview'),
  field('carriagePosition', 'Shuttle travel inspection', '%', 0, 100, 5, 'Preview'),
  field('shelfPosition', 'Support shelf inspection', '%', 0, 100, 5, 'Preview'),
  {
    key: 'showGuards',
    label: 'Show guards',
    type: 'boolean',
    group: 'Preview',
    description: 'Hide for mechanism inspection only.',
  },
];
