import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: 'set',
  diameter: 28,
  bore: 12,
  length: 12,
  screw: 4,
  detail: 'envelope',
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'form',
    label: 'Collar form',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'set', label: 'Set-screw collar' },
      { value: 'split', label: 'Split clamp collar' },
    ],
  },
  {
    key: 'diameter',
    label: 'Outside diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'bore',
    label: 'Shaft bore',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'length',
    label: 'Axial length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'screw',
    label: 'Fastening screw diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'detail',
    label: 'Model detail',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'envelope', label: 'Envelope \u00b7 assembly fit' },
      { value: 'detailed', label: 'Detailed \u00b7 visible construction' },
    ],
  },
];
