import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: 'sk',
  bore: 12,
  width: 50,
  height: 25,
  depth: 20,
  mountPitch: 36,
  mountHole: 5,
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'form',
    label: 'Support form',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'sk', label: 'Split shaft support' },
      { value: 'shf', label: 'Flange shaft support' },
      { value: 'bk', label: 'Fixed screw support' },
    ],
  },
  {
    key: 'bore',
    label: 'Shaft / bearing bore',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'width',
    label: 'Mounting width',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'height',
    visibleWhen: (p) => p.form !== 'shf',
    label: 'Axis height',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'depth',
    label: 'Support depth',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'mountPitch',
    label: 'Mounting hole spacing',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'mountHole',
    label: 'Mounting hole diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
];
