import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: 'rigid',
  diameter: 30,
  bore: 8,
  length: 40,
  gap: 10,
  detail: 'envelope',
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'form',
    label: 'Coupling form',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'rigid', label: 'Rigid sleeve' },
      { value: 'oldham', label: 'Oldham coupling' },
      { value: 'bellows', label: 'Bellows coupling' },
      { value: 'beam', label: 'Slotted beam coupling' },
      { value: 'flange', label: 'Flange coupling' },
    ],
  },
  {
    key: 'diameter',
    label: 'Outside diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'bore',
    label: 'Shaft bore',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'length',
    label: 'Overall length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'gap',
    label: 'Hub separation',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'detail',
    label: 'Model detail',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'envelope', label: 'Envelope \u00b7 assembly fit' },
      { value: 'detailed', label: 'Detailed \u00b7 visible construction' },
    ],
  },
];
