import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  diameter: 18.6,
  length: 65.5,
  count: 2,
  wall: 2,
  clearance: 0.4,
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'diameter',
    label: 'Cell diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'length',
    label: 'Cell length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'count',
    label: 'Cell count',
    type: 'number',
    group: 'Dimensions',
    min: 1,
    max: 8,
    step: 1,
    unit: '',
  },
  {
    key: 'wall',
    label: 'Tray wall',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'clearance',
    label: 'Radial clearance',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2,
    step: 0.1,
    unit: 'mm',
  },
];
