import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = { diameter: 150, bore: 90, height: 20, holes: 8, hole: 6 };
export const parameters: ParameterDefinition[] = [
  {
    key: 'diameter',
    label: 'Outside diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'bore',
    label: 'Centre opening',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'height',
    label: 'Bearing height',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'holes',
    label: 'Holes per bolt circle',
    type: 'number',
    group: 'Dimensions',
    min: 4,
    max: 24,
    step: 1,
    unit: '',
  },
  {
    key: 'hole',
    label: 'Mounting hole diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
];
