import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: 'belt',
  length: 300,
  width: 50,
  height: 16,
  carriage: 60,
  position: 100,
  holePitch: 30,
  detail: 'envelope',
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'form',
    label: 'Guide architecture',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'belt', label: 'Belt-driven slide' },
      { value: 'dovetail', label: 'Dovetail slide' },
      { value: 'telescopic', label: 'Telescopic rail' },
    ],
  },
  {
    key: 'length',
    label: 'Rail length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'width',
    label: 'Rail width',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'height',
    label: 'Rail height',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'carriage',
    label: 'Carriage length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'position',
    label: 'Carriage position',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'holePitch',
    label: 'Carriage mounting pitch',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'detail',
    visibleWhen: (p) => !['dovetail', 'telescopic'].includes(String(p.form)),
    label: 'Model detail',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'envelope', label: 'Envelope \u00b7 assembly fit' },
      { value: 'detailed', label: 'Detailed \u00b7 visible construction' },
    ],
  },
];
