import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  outer: 16,
  width: 11,
  stud: 6,
  collar: 9,
  collarLength: 7.5,
  studLength: 16,
  lip: 0.6,
  hex: 3,
  eccentricity: 0.4,
  angle: 0,
  closure: 'sealed',
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'outer',
    label: 'Roller diameter \u00b7 D',
    type: 'number',
    group: 'Dimensions',
    min: 10,
    max: 100,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'width',
    label: 'Outer ring width \u00b7 C',
    type: 'number',
    group: 'Dimensions',
    min: 6,
    max: 40,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'stud',
    label: 'Stud / thread nominal diameter \u00b7 G',
    type: 'number',
    group: 'Dimensions',
    min: 3,
    max: 30,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'collar',
    label: 'Eccentric collar diameter \u00b7 d\u2091',
    type: 'number',
    group: 'Dimensions',
    min: 5,
    max: 50,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'collarLength',
    label: 'Collar length \u00b7 B\u2083',
    type: 'number',
    group: 'Dimensions',
    min: 3,
    max: 40,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'studLength',
    label: 'Stud projection \u00b7 B\u2082',
    type: 'number',
    group: 'Dimensions',
    min: 6,
    max: 100,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'lip',
    label: 'Head end projection \u00b7 C\u2081',
    type: 'number',
    group: 'Dimensions',
    min: 0.3,
    max: 3,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'hex',
    label: 'Front hex socket across flats \u00b7 H',
    type: 'number',
    group: 'Dimensions',
    min: 1,
    max: 15,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'eccentricity',
    label: 'Eccentricity \u00b7 \u03b5',
    type: 'number',
    group: 'Dimensions',
    min: 0.05,
    max: 5,
    step: 0.05,
    unit: 'mm',
  },
  {
    key: 'angle',
    label: 'Eccentric orientation',
    type: 'number',
    group: 'Position',
    min: 0,
    max: 360,
    step: 1,
    unit: '\u00b0',
  },
  {
    key: 'closure',
    visibleWhen: (_p, state) => state !== 'open',
    label: 'Roller closure',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'sealed', label: 'BUU · rubber seals' },
      { value: 'shielded', label: 'B · metal shields' },
    ],
  },
];
