import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  cell: 30,
  columns: 1,
  rows: 1,
  length: 200,
  slot: 8,
  wall: 2,
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'cell',
    label: 'Cell pitch',
    type: 'number',
    group: 'Dimensions',
    min: 15,
    max: 80,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'columns',
    label: 'Horizontal cells',
    type: 'number',
    group: 'Dimensions',
    min: 1,
    max: 4,
    step: 1,
    unit: '',
  },
  {
    key: 'rows',
    label: 'Vertical cells',
    type: 'number',
    group: 'Dimensions',
    min: 1,
    max: 4,
    step: 1,
    unit: '',
  },
  {
    key: 'length',
    label: 'Cut length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'slot',
    label: 'Slot opening',
    type: 'number',
    group: 'Dimensions',
    min: 3,
    max: 15,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'wall',
    label: 'Lip / web thickness',
    type: 'number',
    group: 'Dimensions',
    min: 1,
    max: 6,
    step: 0.1,
    unit: 'mm',
  },
];
