import type { ParameterDefinition, Parameters, PartDefinition } from '../../core/types';
import models from './lib/models.json';
export const defaults: Parameters = { model: 'speedybee-bls35-mini-v2' };
export const parameters: ParameterDefinition[] = [
  {
    key: 'model',
    label: 'Board / module model',
    type: 'select',
    group: 'Model',
    options: models.map((m) => ({ value: m.id, label: m.name })),
    description:
      'Fixed supplier hardware; select a different model to change dimensions or connections.',
  },
];
export const catalogSelection: NonNullable<PartDefinition['catalogSelection']> = [{ key: 'model' }];
export const catalogFilterFields: ParameterDefinition[] = [
  {
    key: 'manufacturer',
    label: 'Manufacturer',
    type: 'select',
    group: 'Hardware',
    options: [
      {
        value: 'Hobbywing',
        label: 'Hobbywing',
      },
      {
        value: 'SpeedyBee',
        label: 'SpeedyBee',
      },
    ],
  },
  {
    key: 'construction',
    label: 'Construction',
    type: 'select',
    group: 'Hardware',
    options: [
      {
        value: 'Bare PCB',
        label: 'Bare PCB',
      },
      {
        value: 'Wrapped ESC',
        label: 'Wrapped ESC',
      },
    ],
  },
  {
    key: 'connection',
    label: 'Physical connection',
    type: 'select',
    group: 'Hardware',
    options: [
      {
        value: 'Flying leads',
        label: 'Flying leads',
      },
      {
        value: 'Solder pads + FC socket',
        label: 'Solder pads + FC socket',
      },
    ],
  },
  {
    key: 'interface',
    label: 'Interface',
    type: 'select',
    group: 'Hardware',
    options: [
      {
        value: 'DSHOT300/600',
        label: 'DSHOT300/600',
      },
      {
        value: 'PWM',
        label: 'PWM',
      },
    ],
  },
  {
    key: 'width',
    label: 'PCB / body width (X)',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions & ratings',
    min: 0,
    max: 200,
    step: 0.1,
    catalogSummary: true,
  },
  {
    key: 'length',
    label: 'PCB / body length (Y)',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions & ratings',
    min: 0,
    max: 200,
    step: 0.1,
    catalogSummary: true,
  },
  {
    key: 'height',
    label: 'Published height',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions & ratings',
    min: 0,
    max: 100,
    step: 0.1,
    catalogSummary: true,
  },
  {
    key: 'mountX',
    label: 'Mounting pitch X',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions & ratings',
    min: 0,
    max: 100,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'mountY',
    label: 'Mounting pitch Y',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions & ratings',
    min: 0,
    max: 100,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'hole',
    label: 'Mounting bore',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions & ratings',
    min: 0,
    max: 10,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'motorCurrent',
    label: 'Continuous current per motor',
    unit: 'A',
    type: 'number',
    group: 'Dimensions & ratings',
    min: 0,
    max: 200,
    step: 0.1,
    catalogSummary: true,
  },
  {
    key: 'motors',
    label: 'Motor channels',
    unit: '',
    type: 'number',
    group: 'Dimensions & ratings',
    min: 0,
    max: 8,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'cellsMin',
    label: 'Minimum LiPo cells',
    unit: 'S',
    type: 'number',
    group: 'Dimensions & ratings',
    min: 0,
    max: 16,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'cellsMax',
    label: 'Maximum LiPo cells',
    unit: 'S',
    type: 'number',
    group: 'Dimensions & ratings',
    min: 0,
    max: 16,
    step: 0.1,
    catalogSummary: false,
  },
];
