import type { ParameterDefinition, Parameters, PartDefinition } from '../../core/types';
import models from './lib/models.json';
export const defaults: Parameters = { model: 'hobbywing-ubec-3a' };
export const parameters: ParameterDefinition[] = [
  {
    key: 'model',
    label: 'Board / module model',
    type: 'select',
    group: 'Model',
    options: models.map((m) => ({ value: m.id, label: m.name })),
    description:
      'Fixed supplier hardware; select a different model to change dimensions or connections.',
  },
];
export const catalogSelection: NonNullable<PartDefinition['catalogSelection']> = [{ key: 'model' }];
export const catalogFilterFields: ParameterDefinition[] = [
  {
    key: 'manufacturer',
    label: 'Manufacturer',
    type: 'select',
    group: 'Hardware',
    options: [
      {
        value: 'Hobbywing',
        label: 'Hobbywing',
      },
    ],
  },
  {
    key: 'construction',
    label: 'Construction',
    type: 'select',
    group: 'Hardware',
    options: [
      {
        value: 'Enclosed regulator',
        label: 'Enclosed regulator',
      },
    ],
  },
  {
    key: 'connection',
    label: 'Physical connection',
    type: 'select',
    group: 'Hardware',
    options: [
      {
        value: 'Flying leads',
        label: 'Flying leads',
      },
    ],
  },
  {
    key: 'topology',
    label: 'Converter topology',
    type: 'select',
    group: 'Hardware',
    options: [
      {
        value: 'Buck',
        label: 'Buck',
      },
    ],
  },
  {
    key: 'width',
    label: 'PCB / body width (X)',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions & ratings',
    min: 0,
    max: 200,
    step: 0.1,
    catalogSummary: true,
  },
  {
    key: 'length',
    label: 'PCB / body length (Y)',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions & ratings',
    min: 0,
    max: 200,
    step: 0.1,
    catalogSummary: true,
  },
  {
    key: 'height',
    label: 'Published height',
    unit: 'mm',
    type: 'number',
    group: 'Dimensions & ratings',
    min: 0,
    max: 100,
    step: 0.1,
    catalogSummary: true,
  },
  {
    key: 'inputMin',
    label: 'Minimum input voltage',
    unit: 'V',
    type: 'number',
    group: 'Dimensions & ratings',
    min: 0,
    max: 100,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'inputMax',
    label: 'Maximum input voltage',
    unit: 'V',
    type: 'number',
    group: 'Dimensions & ratings',
    min: 0,
    max: 100,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'outputMin',
    label: 'Minimum selectable output',
    unit: 'V',
    type: 'number',
    group: 'Dimensions & ratings',
    min: 0,
    max: 50,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'outputMax',
    label: 'Maximum selectable output',
    unit: 'V',
    type: 'number',
    group: 'Dimensions & ratings',
    min: 0,
    max: 50,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'outputCurrent',
    label: 'Rated output current',
    unit: 'A',
    type: 'number',
    group: 'Dimensions & ratings',
    min: 0,
    max: 100,
    step: 0.1,
    catalogSummary: true,
  },
  {
    key: 'cellsMin',
    label: 'Minimum LiPo cells',
    unit: 'S',
    type: 'number',
    group: 'Dimensions & ratings',
    min: 0,
    max: 16,
    step: 0.1,
    catalogSummary: false,
  },
  {
    key: 'cellsMax',
    label: 'Maximum LiPo cells',
    unit: 'S',
    type: 'number',
    group: 'Dimensions & ratings',
    min: 0,
    max: 16,
    step: 0.1,
    catalogSummary: false,
  },
];
