// Generated by npm run parts:sync. Add or remove a part folder instead of editing this file.
import { registerPartModules } from '../core/part-modules';
import module0 from './ball-bearing/index';
import module1 from './self-aligning-bearing/index';
import module2 from './angular-contact-bearing/index';
import module3 from './double-row-bearing/index';
import module4 from './double-row-angular-contact-bearing/index';
import module5 from './roller-bearing/index';
import module6 from './spherical-roller-bearing/index';
import module7 from './tapered-roller-bearing/index';
import module8 from './needle-bearing/index';
import module9 from './rod-end-bearing/index';
import module10 from './linear-bearing/index';
import module11 from './flanged-linear-bearing/index';
import module12 from './round-flange-linear-bearing/index';
import module13 from './thrust-bearing/index';
import module14 from './flange-2-bolt-bearing/index';
import module15 from './flange-4-bolt-bearing/index';
import module16 from './pillow-block-bearing/index';
import module17 from './insert-bearing/index';
import module18 from './one-way-clutch/index';
import module19 from './csk-clutch/index';
import module20 from './thrust-roller-bearing/index';
import module21 from './spherical-thrust-bearing/index';
import module22 from './combined-bearing/index';
import module23 from './zarn-bearing/index';
import module24 from './plain-bearing/index';
import module25 from './adapter-sleeve/index';
import module26 from './radial-oil-seal/index';
import module27 from './wing-screw/index';
import module28 from './swing-eye-bolt/index';
import module29 from './lifting-eye-bolt/index';
import module30 from './bolt-screw/index';
import module31 from './set-screw/index';
import module32 from './thin-nut/index';
import module33 from './wing-nut/index';
import module34 from './lifting-eye-nut/index';
import module35 from './coupling-nut/index';
import module36 from './high-nut/index';
import module37 from './square-nut/index';
import module38 from './flange-nut/index';
import module39 from './nyloc-nut/index';
import module40 from './cap-nut/index';
import module41 from './metal-lock-nut/index';
import module42 from './square-washer/index';
import module43 from './conical-washer/index';
import module44 from './toothed-washer/index';
import module45 from './threaded-rod/index';
import module46 from './hex-nut/index';
import module47 from './washer/index';
import module48 from './retaining-ring/index';
import module49 from './e-ring/index';
import module50 from './split-lock-washer/index';
import module51 from './spring-pin/index';
import module52 from './cotter-pin/index';
import module53 from './compression-spring/index';
import module54 from './extension-spring/index';
import module55 from './torsion-spring/index';
import module56 from './double-torsion-spring/index';
import module57 from './spiral-spring/index';
import module58 from './worm-drive/index';
import module59 from './spur-gear/index';
import module60 from './helical-gear/index';
import module61 from './bevel-gear/index';
import module62 from './bevel-gear-pair/index';
import module63 from './gear-rack/index';
import module64 from './linear-guide/index';
import module65 from './round-linear-guide/index';
import module66 from './ball-screw/index';
import module67 from './ball-nut/index';
import module68 from './ball-screw-axis/index';
import module69 from './jaw-coupling/index';
import module70 from './enclosure/index';
import module71 from './servo-arm/index';
import module72 from './servo-gear/index';
import module73 from './clevis/index';
import module74 from './piston/index';
import module75 from './connecting-rod/index';
import module76 from './l-bracket/index';
import module77 from './spacer/index';
import module78 from './aluminium-profile/index';
import module79 from './wheel/index';

export const parts = registerPartModules([
  module0,
  module1,
  module2,
  module3,
  module4,
  module5,
  module6,
  module7,
  module8,
  module9,
  module10,
  module11,
  module12,
  module13,
  module14,
  module15,
  module16,
  module17,
  module18,
  module19,
  module20,
  module21,
  module22,
  module23,
  module24,
  module25,
  module26,
  module27,
  module28,
  module29,
  module30,
  module31,
  module32,
  module33,
  module34,
  module35,
  module36,
  module37,
  module38,
  module39,
  module40,
  module41,
  module42,
  module43,
  module44,
  module45,
  module46,
  module47,
  module48,
  module49,
  module50,
  module51,
  module52,
  module53,
  module54,
  module55,
  module56,
  module57,
  module58,
  module59,
  module60,
  module61,
  module62,
  module63,
  module64,
  module65,
  module66,
  module67,
  module68,
  module69,
  module70,
  module71,
  module72,
  module73,
  module74,
  module75,
  module76,
  module77,
  module78,
  module79,
]);
