// Generated by npm run parts:sync. Add or remove a part folder instead of editing this file.
import { registerPartModules } from '../core/part-modules';
import module0 from './ball-bearing/index';
import module1 from './self-aligning-bearing/index';
import module2 from './angular-contact-bearing/index';
import module3 from './double-row-bearing/index';
import module4 from './double-row-angular-contact-bearing/index';
import module5 from './roller-bearing/index';
import module6 from './spherical-roller-bearing/index';
import module7 from './tapered-roller-bearing/index';
import module8 from './needle-bearing/index';
import module9 from './rod-end-bearing/index';
import module10 from './linear-bearing/index';
import module11 from './flanged-linear-bearing/index';
import module12 from './round-flange-linear-bearing/index';
import module13 from './thrust-bearing/index';
import module14 from './flange-2-bolt-bearing/index';
import module15 from './flange-4-bolt-bearing/index';
import module16 from './pillow-block-bearing/index';
import module17 from './insert-bearing/index';
import module18 from './one-way-clutch/index';
import module19 from './csk-clutch/index';
import module20 from './thrust-roller-bearing/index';
import module21 from './spherical-thrust-bearing/index';
import module22 from './combined-bearing/index';
import module23 from './zarn-bearing/index';
import module24 from './plain-bearing/index';
import module25 from './adapter-sleeve/index';
import module26 from './radial-oil-seal/index';
import module27 from './wing-screw/index';
import module28 from './swing-eye-bolt/index';
import module29 from './lifting-eye-bolt/index';
import module30 from './bolt-screw/index';
import module31 from './set-screw/index';
import module32 from './thin-nut/index';
import module33 from './wing-nut/index';
import module34 from './lifting-eye-nut/index';
import module35 from './coupling-nut/index';
import module36 from './high-nut/index';
import module37 from './square-nut/index';
import module38 from './flange-nut/index';
import module39 from './nyloc-nut/index';
import module40 from './cap-nut/index';
import module41 from './metal-lock-nut/index';
import module42 from './square-washer/index';
import module43 from './conical-washer/index';
import module44 from './toothed-washer/index';
import module45 from './threaded-rod/index';
import module46 from './hex-nut/index';
import module47 from './washer/index';
import module48 from './retaining-ring/index';
import module49 from './e-ring/index';
import module50 from './split-lock-washer/index';
import module51 from './spring-pin/index';
import module52 from './cotter-pin/index';
import module53 from './compression-spring/index';
import module54 from './extension-spring/index';
import module55 from './torsion-spring/index';
import module56 from './double-torsion-spring/index';
import module57 from './spiral-spring/index';
import module58 from './worm-drive/index';
import module59 from './spur-gear/index';
import module60 from './helical-gear/index';
import module61 from './bevel-gear/index';
import module62 from './bevel-gear-pair/index';
import module63 from './gear-rack/index';
import module64 from './linear-guide/index';
import module65 from './round-linear-guide/index';
import module66 from './ball-screw/index';
import module67 from './ball-nut/index';
import module68 from './ball-screw-axis/index';
import module69 from './jaw-coupling/index';
import module70 from './enclosure/index';
import module71 from './servo-arm/index';
import module72 from './servo-gear/index';
import module73 from './clevis/index';
import module74 from './piston/index';
import module75 from './connecting-rod/index';
import module76 from './l-bracket/index';
import module77 from './spacer/index';
import module78 from './aluminium-profile/index';
import module79 from './wheel/index';
import module80 from './holding-electromagnet/index';
import module81 from './tubular-solenoid/index';
import module82 from './open-frame-solenoid/index';
import module83 from './servo-motor/index';
import module84 from './lifting-surface/index';
import module85 from './stepper-motor/index';
import module86 from './bldc-motor/index';
import module87 from './camera/index';
import module88 from './flight-controller/index';
import module89 from './bec/index';
import module90 from './esc/index';
import module91 from './dc-dc-converter/index';
import module92 from './raspberry-pi/index';
import module93 from './nanopi/index';
import module94 from './esp32/index';
import module95 from './nrf52840/index';
import module96 from './lora-module/index';
import module97 from './rp-microcontroller/index';
import module98 from './arduino/index';
import module99 from './srs-connector/index';
import module100 from './lipo-battery/index';
import module101 from './li-ion-cell/index';
import module102 from './standard-battery/index';
import module103 from './thread-tool/index';
import module104 from './co2-cartridge/index';
import module105 from './srs-igniter/index';
import module106 from './srs-retainer/index';
import module107 from './aircraft-airframe/index';
import module108 from './model-rocket-airframe/index';
import module109 from './rocket-airbrakes/index';
import module110 from './rocket-release/index';
import module111 from './boat-hull/index';
import module112 from './multicopter-frame/index';
import module113 from './dowel-pin/index';
import module114 from './t-slot-nut/index';
import module115 from './threaded-insert/index';
import module116 from './blind-rivet/index';
import module117 from './shaft-key/index';
import module118 from './shaft/index';
import module119 from './shaft-collar/index';
import module120 from './plain-bushing/index';
import module121 from './o-ring/index';
import module122 from './seal-profile/index';
import module123 from './vibration-mount/index';
import module124 from './shaft-coupling/index';
import module125 from './universal-joint/index';
import module126 from './bearing-locknut/index';
import module127 from './disc-wave-spring/index';
import module128 from './strut/index';
import module129 from './gearbox/index';
import module130 from './bevel-gearbox-42/index';
import module131 from './differential/index';
import module132 from './belt-drive/index';
import module133 from './chain-drive/index';
import module134 from './cable-hardware/index';
import module135 from './shaft-support/index';
import module136 from './lead-screw-axis/index';
import module137 from './linear-stage/index';
import module138 from './industrial-motor/index';
import module139 from './linear-actuator/index';
import module140 from './structural-section/index';
import module141 from './slot-profile/index';
import module142 from './sheet-bracket/index';
import module143 from './fluid-cylinder/index';
import module144 from './fluid-fitting/index';
import module145 from './fluid-valve/index';
import module146 from './fluid-pump/index';
import module147 from './fluid-hose/index';
import module148 from './vacuum-cup/index';
import module149 from './machine-hardware/index';
import module150 from './cable-carrier/index';
import module151 from './cooling-fan/index';
import module152 from './heat-sink/index';
import module153 from './din-rail/index';
import module154 from './battery-holder/index';
import module155 from './industrial-sensor/index';
import module156 from './panel-control/index';
import module157 from './electrical-connector/index';
import module158 from './cable-gland/index';
import module159 from './propeller/index';
import module160 from './duct/index';
import module161 from './landing-gear/index';
import module162 from './robot-wheel/index';
import module163 from './track-drive/index';
import module164 from './brake/index';
import module165 from './parallel-gripper/index';
import module166 from './slewing-bearing/index';
import module167 from './linkage-mechanism/index';
import module168 from './tracked-chassis/index';
import module169 from './eccentric-bearing/index';
import module170 from './eccentric-bushing/index';
import module171 from './eccentric-cam-follower/index';
import module172 from './chf-gf5560-180/index';
import module173 from './faulhaber-bx4/index';
import module174 from './faulhaber-am/index';
import module175 from './faulhaber-planetary/index';
import module176 from './faulhaber-linear-actuator/index';
import module177 from './faulhaber-linear-motor/index';

export const parts = registerPartModules([
  module0,
  module1,
  module2,
  module3,
  module4,
  module5,
  module6,
  module7,
  module8,
  module9,
  module10,
  module11,
  module12,
  module13,
  module14,
  module15,
  module16,
  module17,
  module18,
  module19,
  module20,
  module21,
  module22,
  module23,
  module24,
  module25,
  module26,
  module27,
  module28,
  module29,
  module30,
  module31,
  module32,
  module33,
  module34,
  module35,
  module36,
  module37,
  module38,
  module39,
  module40,
  module41,
  module42,
  module43,
  module44,
  module45,
  module46,
  module47,
  module48,
  module49,
  module50,
  module51,
  module52,
  module53,
  module54,
  module55,
  module56,
  module57,
  module58,
  module59,
  module60,
  module61,
  module62,
  module63,
  module64,
  module65,
  module66,
  module67,
  module68,
  module69,
  module70,
  module71,
  module72,
  module73,
  module74,
  module75,
  module76,
  module77,
  module78,
  module79,
  module80,
  module81,
  module82,
  module83,
  module84,
  module85,
  module86,
  module87,
  module88,
  module89,
  module90,
  module91,
  module92,
  module93,
  module94,
  module95,
  module96,
  module97,
  module98,
  module99,
  module100,
  module101,
  module102,
  module103,
  module104,
  module105,
  module106,
  module107,
  module108,
  module109,
  module110,
  module111,
  module112,
  module113,
  module114,
  module115,
  module116,
  module117,
  module118,
  module119,
  module120,
  module121,
  module122,
  module123,
  module124,
  module125,
  module126,
  module127,
  module128,
  module129,
  module130,
  module131,
  module132,
  module133,
  module134,
  module135,
  module136,
  module137,
  module138,
  module139,
  module140,
  module141,
  module142,
  module143,
  module144,
  module145,
  module146,
  module147,
  module148,
  module149,
  module150,
  module151,
  module152,
  module153,
  module154,
  module155,
  module156,
  module157,
  module158,
  module159,
  module160,
  module161,
  module162,
  module163,
  module164,
  module165,
  module166,
  module167,
  module168,
  module169,
  module170,
  module171,
  module172,
  module173,
  module174,
  module175,
  module176,
  module177,
]);
