import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: 'parallel',
  diameter: 80,
  length: 90,
  shaft: 12,
  shaftLength: 25,
  mountPitch: 60,
  mountHole: 5,
  stages: 1,
  detail: 'detailed',
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'form',
    label: 'Shaft arrangement',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'parallel', label: 'Spur reducer · parallel · 2:1' },
      { value: 'worm', label: 'Miter gearbox · right angle · 1:1' },
      { value: 'planetary', label: 'Planetary reducer · coaxial · 4:1 per stage' },
    ],
  },
  {
    key: 'diameter',
    label: 'Housing width / diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'length',
    label: 'Housing length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'shaft',
    label: 'Shaft diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'shaftLength',
    label: 'Shaft projection',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'mountPitch',
    visibleWhen: (_, state) => state !== 'internals',
    label: 'Mounting bolt circle',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'mountHole',
    visibleWhen: (_, state) => state !== 'internals',
    label: 'Mounting hole diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'stages',
    visibleWhen: (p, state) =>
      p.form === 'planetary' && (p.detail === 'detailed' || state === 'internals'),
    label: 'Number of stages',
    type: 'number',
    group: 'Dimensions',
    min: 1,
    max: 3,
    step: 1,
    unit: '',
  },
  {
    key: 'detail',
    visibleWhen: (_, state) => state !== 'internals',
    label: 'Model detail',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'envelope', label: 'Envelope \u00b7 assembly fit' },
      { value: 'detailed', label: 'Detailed \u00b7 visible construction' },
    ],
  },
];
