import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: 'air',
  diameter: 120,
  hub: 22,
  bore: 5,
  hubHeight: 12,
  blades: 2,
  chord: 20,
  thickness: 12,
  rootAngle: 30,
  tipAngle: 12,
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'form',
    label: 'Rotor family',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'air', label: 'Air propeller' },
      { value: 'marine', label: 'Marine propeller' },
      { value: 'axial', label: 'Axial impeller' },
      { value: 'centrifugal', label: 'Centrifugal impeller' },
    ],
  },
  {
    key: 'diameter',
    label: 'Rotor diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'hub',
    label: 'Hub diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'bore',
    label: 'Shaft bore',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'hubHeight',
    label: 'Hub height',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'blades',
    label: 'Blade count',
    type: 'number',
    group: 'Dimensions',
    min: 2,
    max: 16,
    step: 1,
    unit: '',
  },
  {
    key: 'chord',
    visibleWhen: (p) => p.form !== 'centrifugal',
    label: 'Root chord',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'thickness',
    visibleWhen: (p) => p.form !== 'centrifugal',
    label: 'Blade thickness ratio',
    type: 'number',
    group: 'Dimensions',
    min: 4,
    max: 25,
    step: 0.1,
    unit: '%',
  },
  {
    key: 'rootAngle',
    visibleWhen: (p) => p.form !== 'centrifugal',
    label: 'Root blade angle',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 65,
    step: 0.1,
    unit: '\u00b0',
  },
  {
    key: 'tipAngle',
    visibleWhen: (p) => p.form !== 'centrifugal',
    label: 'Tip blade angle',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 60,
    step: 0.1,
    unit: '\u00b0',
  },
];
