import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  shaftProfile: 'shouldered-d',
  shaftDiameter: 8,
  shaftLength: 21,
  flatThickness: 7,
  flatLength: 15,
  shaftAngle: 0,
  detail: 'complete',
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'shaftProfile',
    label: 'Output shaft profile',
    type: 'select',
    group: 'Output shaft',
    options: [
      { value: 'full-d', label: 'D-flat \u00b7 full projecting length' },
      { value: 'shouldered-d', label: 'D-flat \u00b7 round shoulder' },
    ],
  },
  {
    key: 'detail',
    visibleWhen: (_p, state) => state === 'assembled',
    label: 'Assembly detail',
    type: 'select',
    group: 'Display',
    options: [
      { value: 'complete', label: 'Complete mechanism' },
      { value: 'lightweight', label: 'Lightweight \u00b7 housing and motor' },
    ],
  },
  {
    key: 'shaftDiameter',
    label: 'Shaft diameter',
    type: 'number',
    group: 'Output shaft',
    min: 4,
    max: 10,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'shaftLength',
    label: 'Shaft projection from cover',
    type: 'number',
    group: 'Output shaft',
    min: 10,
    max: 50,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'flatThickness',
    label: 'D-shaft thickness across flat',
    type: 'number',
    group: 'Output shaft',
    min: 2,
    max: 10,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'flatLength',
    visibleWhen: (p) => p.shaftProfile === 'shouldered-d',
    label: 'Flat length from shaft tip',
    type: 'number',
    group: 'Output shaft',
    min: 3,
    max: 40,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'shaftAngle',
    label: 'Shaft flat orientation',
    type: 'number',
    group: 'Output shaft',
    min: 0,
    max: 360,
    step: 1,
    unit: '\u00b0',
  },
];
