import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: 'slide',
  length: 16,
  width: 10,
  height: 6,
  neck: 6,
  bore: 5,
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'form',
    label: 'Nut form',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'slide', label: 'Sliding T nut' },
      { value: 'hammer', label: 'Hammer-head nut' },
    ],
  },
  {
    key: 'length',
    label: 'Nut length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'width',
    label: 'Base width',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'height',
    label: 'Total height',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'neck',
    label: 'Slot neck width',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'bore',
    label: 'Thread nominal diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
];
