import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: 'fork',
  wheels: 'single',
  wheel: 60,
  width: 18,
  strut: 115,
  rod: 14,
  axle: 6,
  forkWall: 4,
  clearance: 3,
  plate: 36,
  braceSpan: 65,
  kneeOffset: 12,
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'form',
    label: 'Construction',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'fork', label: 'Fork strut' },
      { value: 'braced', label: 'Strut with diagonal brace' },
      { value: 'folding', label: 'Strut with two-link brace' },
    ],
  },
  {
    key: 'wheels',
    label: 'Wheel arrangement',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'single', label: 'Single wheel' },
      { value: 'twin', label: 'Twin wheels' },
    ],
  },
  {
    key: 'wheel',
    label: 'Wheel diameter',
    type: 'number',
    group: 'Wheels',
    min: 10,
    max: 1000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'width',
    label: 'Tyre width',
    type: 'number',
    group: 'Wheels',
    min: 3,
    max: 300,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'axle',
    label: 'Axle diameter',
    type: 'number',
    group: 'Wheels',
    min: 2,
    max: 100,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'clearance',
    label: 'Tyre / fork clearance',
    type: 'number',
    group: 'Wheels',
    min: 1,
    max: 50,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'strut',
    label: 'Axle to upper pivot',
    type: 'number',
    group: 'Strut & mount',
    min: 30,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'rod',
    label: 'Outer strut diameter',
    type: 'number',
    group: 'Strut & mount',
    min: 6,
    max: 200,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'forkWall',
    label: 'Fork / bracket thickness',
    type: 'number',
    group: 'Strut & mount',
    min: 2,
    max: 50,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'plate',
    label: 'Mounting plate width',
    type: 'number',
    group: 'Strut & mount',
    min: 15,
    max: 500,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'braceSpan',
    label: 'Upper brace anchor offset',
    type: 'number',
    group: 'Brace',
    min: 20,
    max: 1000,
    step: 0.1,
    unit: 'mm',
    visibleWhen: (p) => p.form !== 'fork',
  },
  {
    key: 'kneeOffset',
    label: 'Brace knee offset',
    type: 'number',
    group: 'Brace',
    min: 0,
    max: 200,
    step: 0.1,
    unit: 'mm',
    visibleWhen: (p) => p.form === 'folding',
  },
];
