import type { Parameters, PartDefinition } from './types';

import { modelEvidence } from './model-evidence';
import { validateParameters } from './validation';

/** A standalone macro that adds a solid or assembly to the active document. */
export function generateScript(
  part: PartDefinition,
  parameters: Parameters,
  state: string,
  presetId?: string,
): string {
  const errors = validateParameters(part, parameters, state);
  if (errors.length) throw new Error(errors.join(' '));
  const body = part
    .python(parameters, state)
    .split('\n')
    .map((line) => `        ${line}`)
    .join('\n');
  const evidence = modelEvidence(part, parameters, presetId);
  const featureName = `ProtoLab_${part.id.replace(/[^a-zA-Z0-9_]/g, '_')}`;
  const expectedDimensions = JSON.stringify(part.dimensions(parameters, state));
  const catalog = part.presets.find((preset) => preset.id === evidence.presetId)?.catalog;
  const catalogProperties = catalog
    ? `
        obj.addProperty("App::PropertyString", "CatalogDesignation", "ProtoLab")
        obj.CatalogDesignation = ${JSON.stringify(catalog.designation)}
        obj.addProperty("App::PropertyString", "CatalogSource", "ProtoLab")
        obj.CatalogSource = ${JSON.stringify(catalog.sourceUrl)}
        obj.addProperty("App::PropertyString", "CatalogDimensions", "ProtoLab")
        obj.CatalogDimensions = ${JSON.stringify(JSON.stringify(Object.fromEntries(catalog.verifiedParameters.map((key) => [key, parameters[key]]))))}${
          catalog.attributes
            ? `
        obj.addProperty("App::PropertyString", "CatalogAttributes", "ProtoLab")
        obj.CatalogAttributes = ${JSON.stringify(JSON.stringify(catalog.attributes))}
        obj.addProperty("App::PropertyString", "CatalogAttributeConditions", "ProtoLab")
        obj.CatalogAttributeConditions = ${JSON.stringify(JSON.stringify(catalog.attributeConditions ?? {}))}`
            : ''
        }`
    : '';
  return `# Generated by ProtoLab. Dimensions are in millimetres; Z is up.
# ${part.name}
# ${part.notes || 'A prototype geometry reference.'}
# Run this file as a FreeCAD macro, or use the one-line console command.
# Expand an assembly in the model tree to select, hide or move its components.
import FreeCAD as App
import Part
import math


def _protolab_create():
    doc = App.ActiveDocument or App.newDocument("ProtoLab")
    doc.openTransaction(${JSON.stringify(`Create ${part.name}`)})
    created_objects = []
    try:
        component_labels = None
        component_colors = None
        component_metadata = None
${body}
        if shape.isNull() or not shape.isValid():
            raise ValueError("The generated CAD shape is invalid.")
        if not shape.Solids or shape.Volume <= 0:
            raise ValueError("The generated CAD shape has no solid volume.")
        bounds = shape.optimalBoundingBox(False, False)
        actual_dimensions = (bounds.XLength, bounds.YLength, bounds.ZLength)
        expected_dimensions = ${expectedDimensions}
        # Trimmed helical faces can have conservative analytical bounds outside
        # their trims. Refine with a 0.005 mm surface mesh before rejecting them.
        if any(abs(actual - expected) > max(0.1, expected * 0.01) for actual, expected in zip(actual_dimensions, expected_dimensions)):
            shape.tessellate(0.005)
            bounds = shape.optimalBoundingBox(True, False)
            actual_dimensions = (bounds.XLength, bounds.YLength, bounds.ZLength)
        if any(abs(actual - expected) > max(0.1, expected * 0.01) for actual, expected in zip(actual_dimensions, expected_dimensions)):
            raise ValueError("The generated CAD dimensions do not match the configured part.")
        # A compound preserves physical component boundaries supplied by the generator.
        # Keep nested compounds together, such as a cage made from several CAD solids.
        component_shapes = shape.childShapes() if shape.ShapeType == "Compound" else [shape]
        if component_labels is not None and len(component_labels) != len(component_shapes):
            raise ValueError("Component labels do not match the generated assembly.")
        if component_colors is not None and len(component_colors) != len(component_shapes):
            raise ValueError("Component colors do not match the generated assembly.")
        if component_metadata is not None and len(component_metadata) != len(component_shapes):
            raise ValueError("Component manufacturing metadata does not match the assembly.")
        display_objects = []
        if len(component_shapes) > 1:
            obj = doc.addObject("App::Part", ${JSON.stringify(featureName)})
            created_objects.append(obj.Name)
            for index, component_shape in enumerate(component_shapes):
                if component_shape.isNull() or not component_shape.isValid() or not component_shape.Solids or component_shape.Volume <= 0:
                    raise ValueError("An assembly component has no valid solid volume.")
                child = doc.addObject("Part::Feature", ${JSON.stringify(featureName + '_Component')} + str(index + 1))
                created_objects.append(child.Name)
                child.Label = component_labels[index] if component_labels is not None else "Component %02d" % (index + 1)
                child.Shape = component_shape
                child.addProperty("App::PropertyInteger", "ComponentIndex", "ProtoLab")
                child.ComponentIndex = index + 1
                if component_metadata is not None:
                    for key, value in component_metadata[index].items():
                        child.addProperty("App::PropertyString", key, "Manufacturing")
                        setattr(child, key, str(value))
                child.addProperty("App::PropertyPlacement", "AssemblyPlacement", "ProtoLab")
                child.AssemblyPlacement = child.Placement
                obj.addObject(child)
                display_objects.append(child)
        else:
            obj = doc.addObject("Part::Feature", ${JSON.stringify(featureName)})
            created_objects.append(obj.Name)
            obj.Shape = shape
            display_objects.append(obj)
        obj.Label = ${JSON.stringify(part.name)}
        obj.addProperty("App::PropertyString", "Generator", "ProtoLab")
        obj.Generator = "ProtoLab 3D"
        obj.addProperty("App::PropertyString", "PartId", "ProtoLab")
        obj.PartId = ${JSON.stringify(part.id)}
        obj.addProperty("App::PropertyString", "Configuration", "ProtoLab")
        obj.Configuration = ${JSON.stringify(JSON.stringify(parameters))}
        obj.addProperty("App::PropertyString", "ModelState", "ProtoLab")
        obj.ModelState = ${JSON.stringify(state)}${catalogProperties}
        obj.addProperty("App::PropertyString", "GeometryEvidence", "ProtoLab")
        obj.GeometryEvidence = ${JSON.stringify(JSON.stringify(evidence))}
        if App.GuiUp:
            for index, display_object in enumerate(display_objects):
                display_object.ViewObject.ShapeColor = tuple(component_colors[index]) if component_colors is not None else (0.62, 0.70, 0.78)
        doc.recompute()
        doc.commitTransaction()
    except Exception:
        doc.abortTransaction()
        # Headless documents can have undo disabled, so abortTransaction alone
        # does not guarantee that partially created objects are removed.
        for object_name in reversed(created_objects):
            if doc.getObject(object_name) is not None:
                doc.removeObject(object_name)
        doc.recompute()
        raise
    if App.GuiUp:
        import FreeCADGui as Gui
        Gui.activeDocument().activeView().viewAxonometric()
        Gui.activeDocument().activeView().fitAll()
    return obj


_protolab_create()
`;
}

/** FreeCAD's interactive console requires multiline code wrapped in exec(). */
export function consoleCommand(script: string): string {
  return `exec(${JSON.stringify(script)})`;
}
