import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: 'gt2',
  pitch: 2,
  teeth: 20,
  centres: 80,
  width: 6,
  thickness: 1.5,
  bore: 5,
  detail: 'envelope',
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'form',
    label: 'Belt family',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'gt2', label: 'GT-family \u00b7 2 mm pitch' },
      { value: 'htd3', label: 'HTD \u00b7 3 mm pitch' },
      { value: 'htd5', label: 'HTD \u00b7 5 mm pitch' },
      { value: 'htd8', label: 'HTD \u00b7 8 mm pitch' },
      { value: 't5', label: 'T \u00b7 5 mm pitch' },
      { value: 't10', label: 'T \u00b7 10 mm pitch' },
      { value: 'v', label: 'V-belt' },
      { value: 'poly', label: 'Poly-V belt' },
    ],
  },
  {
    key: 'pitch',
    label: 'Tooth pitch',
    type: 'number',
    group: 'Dimensions',
    min: 0.5,
    max: 20,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'teeth',
    label: 'Pulley tooth count',
    type: 'number',
    group: 'Dimensions',
    min: 12,
    max: 100,
    step: 1,
    unit: '',
  },
  {
    key: 'centres',
    label: 'Shaft centre distance',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'width',
    label: 'Belt width',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'thickness',
    label: 'Belt radial thickness',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'bore',
    label: 'Pulley shaft bore',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'detail',
    label: 'Model detail',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'envelope', label: 'Envelope \u00b7 assembly fit' },
      { value: 'detailed', label: 'Detailed \u00b7 visible construction' },
    ],
  },
];
