import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  seat: 6,
  bore: 3,
  length: 5,
  acrossFlats: 10,
  head: 3,
  eccentricity: 0.3,
  angle: 0,
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'seat',
    label: 'Bearing seat diameter \u00b7 D',
    type: 'number',
    group: 'Dimensions',
    min: 2,
    max: 100,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'bore',
    label: 'Through bore \u00b7 V',
    type: 'number',
    group: 'Dimensions',
    min: 1,
    max: 80,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'length',
    label: 'Bearing seat length \u00b7 F',
    type: 'number',
    group: 'Dimensions',
    min: 1,
    max: 100,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'acrossFlats',
    label: 'Hex head across flats \u00b7 B',
    type: 'number',
    group: 'Dimensions',
    min: 3,
    max: 120,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'head',
    label: 'Hex head thickness \u00b7 T',
    type: 'number',
    group: 'Dimensions',
    min: 0.5,
    max: 20,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'eccentricity',
    label: 'Eccentricity \u00b7 e',
    type: 'number',
    group: 'Dimensions',
    min: 0.05,
    max: 20,
    step: 0.05,
    unit: 'mm',
  },
  {
    key: 'angle',
    label: 'Eccentric orientation',
    type: 'number',
    group: 'Position',
    min: 0,
    max: 360,
    step: 1,
    unit: '\u00b0',
  },
];
