import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  bore: 30,
  outer: 70,
  outerWidth: 16,
  innerWidth: 18.5,
  eccentricity: 4.5,
  keyWidth: 8,
  keyDepth: 2,
  angle: 0,
  closure: 'sealed',
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'bore',
    label: 'Shaft bore',
    type: 'number',
    group: 'Dimensions',
    min: 4,
    max: 100,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'outer',
    label: 'Outer diameter',
    type: 'number',
    group: 'Dimensions',
    min: 12,
    max: 200,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'outerWidth',
    label: 'Outer ring width',
    type: 'number',
    group: 'Dimensions',
    min: 4,
    max: 60,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'innerWidth',
    label: 'Inner ring width',
    type: 'number',
    group: 'Dimensions',
    min: 4,
    max: 70,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'eccentricity',
    label: 'Eccentricity \u00b7 reconstructed',
    type: 'number',
    group: 'Dimensions',
    min: 0.05,
    max: 20,
    step: 0.05,
    unit: 'mm',
  },
  {
    key: 'keyWidth',
    label: 'Keyway width \u00b7 reconstructed',
    type: 'number',
    group: 'Dimensions',
    min: 1,
    max: 25,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'keyDepth',
    label: 'Keyway depth \u00b7 reconstructed',
    type: 'number',
    group: 'Dimensions',
    min: 0.2,
    max: 10,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'angle',
    label: 'Eccentric orientation',
    type: 'number',
    group: 'Position',
    min: 0,
    max: 360,
    step: 1,
    unit: '\u00b0',
  },
  {
    key: 'closure',
    visibleWhen: (_p, state) => state !== 'open',
    label: 'Bearing closure',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'sealed', label: 'Two rubber seals' },
      { value: 'open', label: 'Open · inspect rolling elements' },
    ],
  },
];
