import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: '3-2',
  length: 60,
  width: 25,
  height: 25,
  port: 6,
  mount: 4,
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'form',
    label: 'Unit type',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: '3-2', label: '3/2 directional valve' },
      { value: '5-2', label: '5/2 directional valve' },
      { value: '5-3', label: '5/3 directional valve' },
      { value: 'check', label: 'Check valve' },
      { value: 'throttle', label: 'Throttle / flow control' },
      { value: 'relief', label: 'Relief valve' },
      { value: 'ball', label: 'Ball valve' },
      { value: 'frl', label: 'Filter-regulator-lubricator' },
      { value: 'ejector', label: 'Vacuum ejector' },
    ],
  },
  {
    key: 'length',
    label: 'Block length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'width',
    label: 'Block width',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'height',
    label: 'Block height',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'port',
    label: 'Port bore',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'mount',
    label: 'Mounting bore',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
];
