import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: 'disc',
  diameter: 40,
  bore: 20,
  height: 3,
  thickness: 1,
  waves: 3,
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'form',
    label: 'Spring form',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'disc', label: 'Conical disc spring' },
      { value: 'wave', label: 'Wave washer' },
      { value: 'leaf', label: 'Leaf spring' },
    ],
  },
  {
    key: 'diameter',
    label: 'Disc outside diameter / leaf length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'bore',
    label: 'Disc bore / leaf width',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'height',
    label: 'Free rise',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'thickness',
    label: 'Material thickness',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'waves',
    label: 'Wave count',
    type: 'number',
    group: 'Dimensions',
    min: 2,
    max: 8,
    step: 1,
    unit: '',
  },
];
