import type { Parameters } from '../../../../core/types';

export const lmkReference: Record<number, Parameters> = {
  '6': {
    bore: 6,
    outer: 12,
    flangeDiameter: 28,
    flangeThickness: 5,
    boltCircle: 20,
    flangeWidth: 22,
    holeDiameter: 3.4,
    counterbore: 6.5,
    counterDepth: 3.3,
    circuits: 4,
  },
  '8': {
    bore: 8,
    outer: 15,
    flangeDiameter: 32,
    flangeThickness: 5,
    boltCircle: 24,
    flangeWidth: 25,
    holeDiameter: 3.4,
    counterbore: 6.5,
    counterDepth: 3.3,
    circuits: 4,
  },
  '10': {
    bore: 10,
    outer: 19,
    flangeDiameter: 40,
    flangeThickness: 6,
    boltCircle: 29,
    flangeWidth: 30,
    holeDiameter: 4.5,
    counterbore: 8,
    counterDepth: 4.4,
    circuits: 4,
  },
  '12': {
    bore: 12,
    outer: 21,
    flangeDiameter: 42,
    flangeThickness: 6,
    boltCircle: 32,
    flangeWidth: 32,
    holeDiameter: 4.5,
    counterbore: 8,
    counterDepth: 4.4,
    circuits: 4,
  },
  '13': {
    bore: 13,
    outer: 23,
    flangeDiameter: 43,
    flangeThickness: 6,
    boltCircle: 33,
    flangeWidth: 34,
    holeDiameter: 4.5,
    counterbore: 8,
    counterDepth: 4.4,
    circuits: 4,
  },
  '16': {
    bore: 16,
    outer: 28,
    flangeDiameter: 48,
    flangeThickness: 6,
    boltCircle: 38,
    flangeWidth: 37,
    holeDiameter: 4.5,
    counterbore: 8,
    counterDepth: 4.4,
    circuits: 5,
  },
  '20': {
    bore: 20,
    outer: 32,
    flangeDiameter: 54,
    flangeThickness: 8,
    boltCircle: 43,
    flangeWidth: 42,
    holeDiameter: 5.5,
    counterbore: 9.5,
    counterDepth: 5.4,
    circuits: 5,
  },
  '25': {
    bore: 25,
    outer: 40,
    flangeDiameter: 62,
    flangeThickness: 8,
    boltCircle: 51,
    flangeWidth: 50,
    holeDiameter: 5.5,
    counterbore: 9.5,
    counterDepth: 5.4,
    circuits: 6,
  },
  '30': {
    bore: 30,
    outer: 45,
    flangeDiameter: 74,
    flangeThickness: 10,
    boltCircle: 60,
    flangeWidth: 58,
    holeDiameter: 6.6,
    counterbore: 11,
    counterDepth: 6.5,
    circuits: 6,
  },
  '35': {
    bore: 35,
    outer: 52,
    flangeDiameter: 82,
    flangeThickness: 10,
    boltCircle: 67,
    flangeWidth: 64,
    holeDiameter: 6.6,
    counterbore: 11,
    counterDepth: 6.5,
    circuits: 6,
  },
  '40': {
    bore: 40,
    outer: 60,
    flangeDiameter: 96,
    flangeThickness: 13,
    boltCircle: 78,
    flangeWidth: 75,
    holeDiameter: 9,
    counterbore: 14,
    counterDepth: 8.6,
    circuits: 6,
  },
  '50': {
    bore: 50,
    outer: 80,
    flangeDiameter: 116,
    flangeThickness: 13,
    boltCircle: 98,
    flangeWidth: 92,
    holeDiameter: 9,
    counterbore: 14,
    counterDepth: 8.6,
    circuits: 6,
  },
  '60': {
    bore: 60,
    outer: 90,
    flangeDiameter: 134,
    flangeThickness: 18,
    boltCircle: 112,
    flangeWidth: 106,
    holeDiameter: 11,
    counterbore: 17.5,
    counterDepth: 10.8,
    circuits: 6,
  },
};

export const lmkReferenceUrl =
  'https://www.hepcomotion.com/wp-content/uploads/2015/10/UK-Ball-Bushings-Catalogue-2.2-2023.pdf';
