import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  mechanism: 'spiral',
  sequence: 0,
  tubeOD: 90,
  tubeID: 86,
  bayLength: 150,
  noseLength: 80,
  packDiameter: 50,
  packLength: 60,
  canopyDiameter: 500,
  separation: 230,
  springTravel: 60,
  springWire: 1.3,
  springCoils: 24,
  springPreload: 10,
  noseMass: 1,
  cassetteMass: 0.2,
  extractionForce: 5,
  guideForce: 1,
  exitSpeed: 1,
  energyFactor: 1.5,
  lockFriction: 0.15,
  hookGuideFriction: 0.15,
  retentionLoad: 1000,
  thrustFriction: 0.08,
  mainReleaseAltitude: 300,
  drogueDiameter: 250,
  gearEfficiency: 0.7,
  servoDerating: 0.5,
  axialGravity: 1,
  packVoltage: 7.4,
  camSweep: 90,
  cellMass: 46,
  batteryTrim: 0,
};
const number = (
  key: string,
  label: string,
  group: string,
  min: number,
  max: number,
  step = 1,
  unit = 'mm',
): ParameterDefinition => ({ key, label, group, type: 'number', min, max, step, unit });
export const parameters: ParameterDefinition[] = [
  {
    key: 'mechanism',
    label: 'Recovery latch',
    group: 'Architecture',
    type: 'select',
    options: [
      { value: 'spiral', label: 'AirBrakes · linear spiral / three hooks' },
      { value: 'sculpted-cam', label: 'AirBrakes · eased spiral / three hooks' },
      { value: 'rotary-ring', label: 'MG996R release · 100T / 40T / 20T' },
    ],
  },
  number('sequence', 'Recovery sequence', 'Motion', 0, 100, 1, '%'),
  number('separation', 'Nose extraction travel', 'Motion', 180, 400),
  number('camSweep', 'Cam servo sweep', 'Motion', 75, 105, 1, '°'),
  number('bayLength', 'Recovery bay length', 'Airframe', 120, 240),
  number('noseLength', 'Nose taper length', 'Airframe', 60, 140),
  number('packDiameter', 'Packed parachute diameter', 'Parachute', 30, 60),
  number('packLength', 'Packed parachute length', 'Parachute', 40, 90),
  number('canopyDiameter', 'Canopy routing diameter', 'Parachute', 300, 1200, 10),
  number('noseMass', 'Separating mass (user estimate)', 'Loads', 0.1, 3, 0.05, 'kg'),
  number('retentionLoad', 'External axial retention load (assumed)', 'Loads', 0, 10000, 50, 'N'),
  number('cassetteMass', 'Cassette and packed parachutes mass', 'Loads', 0.05, 0.6, 0.01, 'kg'),
  number('extractionForce', 'Pack pull force (measure)', 'Loads', 0, 40, 0.5, 'N'),
  number(
    'mainReleaseAltitude',
    'Main chute release target (external controller)',
    'Parachute',
    50,
    1000,
    10,
    'm',
  ),
  number('drogueDiameter', 'Drogue routing diameter', 'Parachute', 150, 400, 10),
  number('thrustFriction', 'Cassette / nose thrust friction (assumed)', 'Drive', 0, 0.3, 0.01, ''),
  number('guideForce', 'Pusher / guide friction allowance', 'Loads', 0, 10, 0.25, 'N'),
  number('axialGravity', 'Adverse axial gravity component', 'Loads', 0, 1, 0.1, 'g'),
  number('exitSpeed', 'Minimum speed after pack clears', 'Loads', 0, 3, 0.1, 'm/s'),
  number('energyFactor', 'Required energy factor', 'Loads', 1, 2.5, 0.1, ''),
  number('springTravel', 'Cassette ejector stroke', 'Guide springs', 30, 65),
  number('springWire', 'Each spring wire diameter', 'Guide springs', 1, 1.5, 0.05),
  number('springCoils', 'Active coils per spring', 'Guide springs', 18, 30, 1, ''),
  number('springPreload', 'Residual spring compression', 'Guide springs', 3, 15, 0.5),
  number('lockFriction', 'Lock friction coefficient (assumed)', 'Drive', 0.05, 0.4, 0.01, ''),
  number('hookGuideFriction', 'Latch support friction (assumed)', 'Drive', 0.05, 0.4, 0.01, ''),
  number('gearEfficiency', 'Drive efficiency (assumed)', 'Drive', 0.3, 0.9, 0.05, ''),
  number('servoDerating', 'Fraction of published stall torque', 'Drive', 0.1, 0.5, 0.05, ''),
  number('packVoltage', 'Loaded 2S pack voltage', 'Electrical', 6, 8.4, 0.1, 'V'),
  number('cellMass', 'Each 18650 mass', 'Electrical', 35, 60, 1, 'g'),
  number('batteryTrim', 'Battery lateral balance trim', 'Electrical', -2, 2, 0.1),
];
