import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: 'fourbar',
  ground: 120,
  crank: 25,
  rod: 110,
  output: 60,
  phase: 35,
  width: 12,
  thickness: 5,
  pin: 4,
  slots: 6,
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'form',
    label: 'Mechanism',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'fourbar', label: 'Four-bar linkage' },
      { value: 'slider', label: 'Slider-crank' },
      { value: 'yoke', label: 'Scotch yoke' },
      { value: 'scissor', label: 'Scissor lift' },
      { value: 'pantograph', label: 'Parallelogram' },
      { value: 'eccentric', label: 'Eccentric cam' },
      { value: 'cam', label: 'Circular eccentric cam and roller' },
      { value: 'ratchet', label: 'Ratchet and pawl' },
      { value: 'geneva', label: 'Geneva indexer' },
    ],
  },
  {
    key: 'ground',
    visibleWhen: (p) => ['fourbar', 'geneva'].includes(String(p.form)),
    label: 'Fixed pivot spacing',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'crank',
    visibleWhen: (p) => ['fourbar', 'slider', 'yoke', 'cam', 'eccentric'].includes(String(p.form)),
    label: 'Crank radius',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'rod',
    visibleWhen: (p) => p.form !== 'geneva',
    label: 'Coupler / link length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'output',
    visibleWhen: (p) => ['fourbar', 'pantograph', 'ratchet'].includes(String(p.form)),
    label: 'Output link length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'phase',
    label: 'Input phase',
    type: 'number',
    group: 'Dimensions',
    min: 0,
    max: 360,
    step: 0.1,
    unit: '\u00b0',
  },
  {
    key: 'width',
    label: 'Link width',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'thickness',
    label: 'Link thickness',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'pin',
    label: 'Pivot bore',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'slots',
    visibleWhen: (p) => ['ratchet', 'geneva'].includes(String(p.form)),
    label: 'Index positions / ratchet teeth',
    type: 'number',
    group: 'Dimensions',
    min: 4,
    max: 12,
    step: 1,
    unit: '',
  },
];
