import type { Parameters, ParameterDefinition } from '../../core/types';
import models from './lib/models.json';
export const defaults: Parameters = { model: '2232S024BX4' };
export const parameters: ParameterDefinition[] = [
  {
    key: 'model',
    label: 'Manufacturer model',
    type: 'select',
    group: 'Catalogue',
    options: models.map((m) => ({ value: m.model, label: m.model })),
  },
];
export const catalogFilterFields: ParameterDefinition[] = [
  {
    key: 'bodyDiameter',
    label: 'Body diameter',
    unit: 'mm',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 100000,
    step: 0.001,
    catalogSummary: true,
  },
  {
    key: 'bodyLength',
    label: 'Body length',
    unit: 'mm',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 100000,
    step: 0.001,
    catalogSummary: true,
  },
  {
    key: 'shaftDiameter',
    label: 'Shaft diameter',
    unit: 'mm',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 100000,
    step: 0.001,
    catalogSummary: false,
  },
  {
    key: 'shaftProjection',
    label: 'Front shaft projection',
    unit: 'mm',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 100000,
    step: 0.001,
    catalogSummary: false,
  },
  {
    key: 'voltage',
    label: 'Nominal voltage',
    unit: 'V',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 100000,
    step: 0.001,
    catalogSummary: true,
  },
  {
    key: 'noLoadSpeed',
    label: 'No-load speed',
    unit: 'rpm',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 100000,
    step: 0.001,
    catalogSummary: false,
  },
  {
    key: 'ratedTorque',
    label: 'Rated torque',
    unit: 'mNm',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 100000,
    step: 0.001,
    catalogSummary: false,
  },
  {
    key: 'stallTorque',
    label: 'Stall torque',
    unit: 'mNm',
    type: 'number',
    group: 'Specifications',
    min: 0,
    max: 100000,
    step: 0.001,
    catalogSummary: false,
  },
];
