import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  width: 40,
  length: 50,
  height: 20,
  base: 3,
  fins: 8,
  fin: 1.2,
  detail: 'envelope',
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'width',
    label: 'Base width',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'length',
    label: 'Extrusion length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'height',
    label: 'Total height',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'base',
    label: 'Base thickness',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'fins',
    label: 'Number of fins',
    type: 'number',
    group: 'Dimensions',
    min: 2,
    max: 30,
    step: 1,
    unit: '',
  },
  {
    key: 'fin',
    label: 'Fin thickness',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'detail',
    label: 'Model detail',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'envelope', label: 'Envelope \u00b7 assembly fit' },
      { value: 'detailed', label: 'Detailed \u00b7 visible construction' },
    ],
  },
];
