import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  width: 70,
  length: 40,
  height: 25,
  opening: 30,
  finger: 40,
  thickness: 8,
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'width',
    label: 'Body width',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'length',
    label: 'Body length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'height',
    label: 'Body height',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'opening',
    label: 'Clear jaw opening',
    type: 'number',
    group: 'Dimensions',
    min: 2,
    max: 200,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'finger',
    label: 'Finger height',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'thickness',
    label: 'Finger thickness',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
];
