import type { ParameterDefinition, Parameters } from '../../core/types';
export const defaults: Parameters = {
  bodyDiameter: 11,
  overallHeight: 22.5,
  capDiameter: 7.6,
  capHeight: 6.6,
  collarDiameter: 8.2,
  baseDiameter: 6.5,
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'bodyDiameter',
    label: 'Housing maximum diameter',
    type: 'number',
    min: 8,
    max: 30,
    step: 0.1,
    unit: 'mm',
    group: 'Overall dimensions',
    description: 'Drawing variant 2: Ø11 ±0.1 mm. Editing creates a custom layout model.',
  },
  {
    key: 'overallHeight',
    label: 'Overall height, including pins',
    type: 'number',
    min: 15,
    max: 60,
    step: 0.1,
    unit: 'mm',
    group: 'Overall dimensions',
    description: 'Drawing variant 2: 22.5 ±0.2 mm, including the fixed 7.3 mm reference pins.',
  },
  {
    key: 'capDiameter',
    label: 'Metal cap diameter',
    type: 'number',
    min: 3,
    max: 25,
    step: 0.1,
    unit: 'mm',
    group: 'Exterior profile',
    description:
      'Default 7.6 mm from the earlier user description; not dimensioned on this drawing.',
  },
  {
    key: 'capHeight',
    label: 'Metal cap height',
    type: 'number',
    min: 1,
    max: 35,
    step: 0.1,
    unit: 'mm',
    group: 'Exterior profile',
    description: 'Approximate exterior height; the remaining housing height adjusts automatically.',
  },
  {
    key: 'collarDiameter',
    label: 'Upper collar diameter',
    type: 'number',
    min: 3,
    max: 28,
    step: 0.1,
    unit: 'mm',
    group: 'Exterior profile',
    description: 'Undimensioned in the drawing; editable layout approximation.',
  },
  {
    key: 'baseDiameter',
    label: 'Lower boss diameter',
    type: 'number',
    min: 5.5,
    max: 28,
    step: 0.1,
    unit: 'mm',
    group: 'Exterior profile',
    description: 'Undimensioned in the drawing. Reference pins do not scale with the boss.',
  },
];
