import type { ParameterDefinition, Parameters } from '../../core/types';
export const defaults: Parameters = {
  feedMode: 'automatic',
  stockGap: 200,
  clearDwell: 1000,
  firstTrim: 24,
  consumedLength: 0,
  showGuards: true,
  profile: 'round',
  profileHeight: 120,
  discharge: 'auto',
  shortPartLimit: 200,
  sidePressure: 6,
  transferPressure: 1,
  measuredTolerance: 0.2,
  slipLimit: 0.5,
  strokePosition: 50,
  tubeDiameter: 120,
  wall: 4,
  cutLength: 250,
  stockLength: 6000,
  angle: 0,
  airPressure: 6,
  friction: 0.25,
  cuttingForce: 150,
  feedResistance: 60,
  runningTorque: 0.5,
  spindleRpm: 2300,
  sawFeed: 2,
  axisError: 0.1,
  gripError: 0.15,
  bladeError: 0.15,
  datumError: 0.1,
  fullStock: false,
};
const number = (
  key: string,
  label: string,
  unit: string,
  min: number,
  max: number,
  step: number,
  group: string,
  description?: string,
): ParameterDefinition => ({
  key,
  label,
  unit,
  type: 'number',
  min,
  max,
  step,
  group,
  description,
});
export const parameters: ParameterDefinition[] = [
  {
    key: 'feedMode',
    label: 'Infeed module',
    type: 'select',
    group: 'Machine modules',
    options: [
      { value: 'automatic', label: 'Automatic · shuttle + gated loading conveyor' },
      {
        value: 'assisted',
        label: 'Assisted · operator loads one bar, automatic measuring/cutting',
      },
      { value: 'manual', label: 'Standalone saw · load under hood, clamp and cut' },
    ],
    description:
      'Same cutting cell and DDCS v4.1. Changing hardware requires isolation, keyed mode selection and module-presence confirmation.',
  },
  number(
    'stockGap',
    'New-bar separation distance',
    'mm',
    160,
    400,
    10,
    'Stock tracking',
    'Distance from the stop blade to the downstream tail-clear beam; next bar remains held at the stop.',
  ),
  number('clearDwell', 'Empty-zone confirmation time', 'ms', 500, 5000, 100, 'Stock tracking'),
  number(
    'firstTrim',
    'First facing trim allowance',
    'mm',
    24,
    300,
    1,
    'Stock tracking',
    'Includes the first facing kerf. Confirm a new faced datum for every bar.',
  ),
  number(
    'consumedLength',
    'Already consumed from this bar',
    'mm',
    0,
    6000,
    1,
    'Stock tracking',
    'Planning ledger includes every finished length and its axial kerf; a new bar is a separate record.',
  ),
  {
    key: 'showGuards',
    label: 'Show guards',
    type: 'boolean',
    group: 'Preview',
    description:
      'Hide only for inspecting the mechanism; does not remove required physical guards.',
  },
  {
    key: 'profile',
    label: 'Stock profile / tooling',
    type: 'select',
    group: 'Workpiece',
    options: [
      { value: 'round', label: 'Round tube · radius inserts' },
      { value: 'square', label: 'Square tube · flat inserts' },
      { value: 'rectangular', label: 'Rectangular tube · flat inserts' },
      { value: 'triangular', label: 'Triangular tube · shaped inserts' },
      { value: 'oval', label: 'Oval tube · shaped inserts' },
      { value: 'custom', label: 'Custom profile · envelope / custom inserts' },
    ],
  },
  number(
    'profileHeight',
    'Profile height',
    'mm',
    30,
    120,
    1,
    'Workpiece',
    'Used for rectangular and custom profile envelopes; custom tooling must match the real section.',
  ),
  number('tubeDiameter', 'Tube diameter / profile width', 'mm', 30, 120, 1, 'Workpiece'),
  number('wall', 'Tube wall', 'mm', 1, 4, 0.1, 'Workpiece'),
  number(
    'cutLength',
    'Finished cut length',
    'mm',
    20,
    500,
    1,
    'Workpiece',
    'Straight-cut length. At a mitre, measured between parallel faces along the tube axis; first trim and angle changes need a new datum.',
  ),
  number(
    'stockLength',
    'Incoming stock length',
    'mm',
    1000,
    6000,
    100,
    'Workpiece',
    '6 m is an adjustable planning assumption, not a supplied stock specification.',
  ),
  number('angle', 'Manual mitre angle', '°', -45, 45, 1, 'Cutting'),
  number(
    'spindleRpm',
    'Spindle setpoint',
    'rpm',
    1000,
    2500,
    50,
    'Cutting',
    'Planning setpoint; the delivered blade rating and spindle balance limit take precedence.',
  ),
  number(
    'sawFeed',
    'Saw rise speed',
    'mm/s',
    0.5,
    5,
    0.5,
    'Cutting',
    'Regulated cutting stroke, not rapid approach. Material trials determine the usable value.',
  ),
  number('airPressure', 'Top clamp regulator', 'bar', 1, 7, 0.1, 'Force checks'),
  number('sidePressure', 'Side clamp regulator', 'bar', 1, 7, 0.1, 'Force checks'),
  number('transferPressure', 'Rolling shoe transfer regulator', 'bar', 0.5, 2, 0.1, 'Force checks'),
  number('measuredTolerance', 'Material encoder stop window', 'mm', 0.05, 0.3, 0.01, 'Measurement'),
  number('slipLimit', 'Axis / material slip trip', 'mm', 0.1, 1, 0.05, 'Measurement'),
  {
    key: 'discharge',
    label: 'Offcut destination',
    type: 'select',
    group: 'Handling',
    options: [
      { value: 'auto', label: 'Automatic by length' },
      { value: 'box', label: 'Short parts to box' },
      { value: 'rollers', label: 'Long parts to roller line' },
    ],
  },
  number('shortPartLimit', 'Automatic box threshold', 'mm', 20, 200, 10, 'Handling'),
  number(
    'strokePosition',
    'Saw stroke inspection',
    '%',
    0,
    100,
    5,
    'Preview',
    'Used in the Stroke inspection model state.',
  ),
  number(
    'friction',
    'Effective grip friction',
    '',
    0.1,
    0.5,
    0.01,
    'Force checks',
    'Assumed measured coefficient including coolant and jaw material.',
  ),
  number(
    'cuttingForce',
    'Required work holding force',
    'N',
    20,
    500,
    10,
    'Force checks',
    'Unverified design load for grip screening; measure cutting loads.',
  ),
  number(
    'feedResistance',
    'Stock feed resistance',
    'N',
    10,
    250,
    5,
    'Force checks',
    'Includes rolling resistance and acceleration. Verify with full stock.',
  ),
  number(
    'runningTorque',
    'Available feed running torque',
    'N·m',
    0.1,
    1.5,
    0.05,
    'Force checks',
    'Conservative planning input; use a torque-speed curve at the actual voltage, not holding torque.',
  ),
  ...[
    ['axisError', 'Axis positioning allowance', 0.1],
    ['gripError', 'Grip/slip allowance', 0.15],
    ['bladeError', 'Blade/runout allowance', 0.15],
    ['datumError', 'Datum/calibration allowance', 0.1],
  ].map(([key, label]) =>
    number(
      String(key),
      String(label),
      'mm',
      0,
      0.5,
      0.01,
      'Accuracy budget',
      'Worst-case allocation, not measured accuracy.',
    ),
  ),
  {
    key: 'fullStock',
    label: 'Show full stock and roller line',
    type: 'boolean',
    group: 'Preview',
    filterable: false,
  },
];
