import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: 'stepped',
  diameter: 20,
  endDiameter: 12,
  length: 150,
  endLength: 30,
  keyWidth: 6,
  keyDepth: 3,
  groove: 1.2,
  teeth: 8,
  detail: 'envelope',
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'form',
    label: 'Shaft surface',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'stepped', label: 'Stepped journals' },
      { value: 'taper', label: 'Tapered end' },
      { value: 'spline', label: 'Straight-sided spline' },
    ],
  },
  {
    key: 'diameter',
    label: 'Centre journal diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'endDiameter',
    label: 'End journal diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'length',
    label: 'Overall shaft length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'endLength',
    label: 'Each end journal length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'keyWidth',
    visibleWhen: (p) => p.form !== 'spline',
    label: 'Keyway width',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'keyDepth',
    visibleWhen: (p) => p.form !== 'spline',
    label: 'Keyway depth',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'groove',
    visibleWhen: (p) => p.detail === 'detailed',
    label: 'Retaining groove width',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'teeth',
    visibleWhen: (p) => p.form === 'spline',
    label: 'Spline tooth count',
    type: 'number',
    group: 'Dimensions',
    min: 4,
    max: 32,
    step: 1,
    unit: '',
  },
  {
    key: 'detail',
    label: 'Model detail',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'envelope', label: 'Envelope \u00b7 assembly fit' },
      { value: 'detailed', label: 'Detailed \u00b7 visible construction' },
    ],
  },
];
