import type { Parameters, ParameterDefinition } from '../../core/types';
export const defaults: Parameters = {
  form: 'u',
  width: 40,
  length: 60,
  height: 30,
  wall: 3,
  hole: 6,
  pitch: 24,
};
export const parameters: ParameterDefinition[] = [
  {
    key: 'form',
    label: 'Bracket form',
    type: 'select',
    group: 'Configuration',
    options: [
      { value: 'u', label: 'U bracket' },
      { value: 'z', label: 'Z bracket' },
    ],
  },
  {
    key: 'width',
    label: 'Bracket width',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'length',
    label: 'Base length',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'height',
    label: 'Flange height',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'wall',
    label: 'Sheet thickness',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'hole',
    label: 'Hole diameter',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
  {
    key: 'pitch',
    label: 'Hole spacing',
    type: 'number',
    group: 'Dimensions',
    min: 0.1,
    max: 2000,
    step: 0.1,
    unit: 'mm',
  },
];
